// Seed script - Direct API with login
const API = "http://localhost:5000";

const commonDocs = [
    { title: "Valid Passport", titleBn: "বৈধ পাসপোর্ট", description: "Minimum 6 months validity with 2 blank pages", descriptionBn: "ন্যূনতম ৬ মাস মেয়াদ ও ২টি খালি পৃষ্ঠা", isRequired: true },
    { title: "Passport Size Photos", titleBn: "পাসপোর্ট সাইজ ছবি", description: "Recent photographs with white background", descriptionBn: "সাদা ব্যাকগ্রাউন্ডে সাম্প্রতিক ছবি", isRequired: true },
    { title: "Visa Application Form", titleBn: "ভিসা আবেদন ফর্ম", description: "Completed and signed application form", descriptionBn: "পূরণকৃত ও স্বাক্ষরিত আবেদন ফর্ম", isRequired: true },
    { title: "Bank Statement", titleBn: "ব্যাংক স্টেটমেন্ট", description: "Last 6 months bank statement", descriptionBn: "শেষ ৬ মাসের ব্যাংক স্টেটমেন্ট", isRequired: true },
    { title: "Hotel Booking", titleBn: "হোটেল বুকিং", description: "Confirmed hotel reservation", descriptionBn: "নিশ্চিত হোটেল রিজার্ভেশন", isRequired: true },
    { title: "Flight Itinerary", titleBn: "ফ্লাইট ইটিনারেরি", description: "Round trip flight booking", descriptionBn: "যাওয়া-আসার ফ্লাইট বুকিং", isRequired: true },
    { title: "Travel Insurance", titleBn: "ট্রাভেল ইন্স্যুরেন্স", description: "Coverage for the entire trip duration", descriptionBn: "সম্পূর্ণ ভ্রমণকালীন কভারেজ", isRequired: false },
    { title: "NOC / Leave Letter", titleBn: "এনওসি / ছুটির চিঠি", description: "No Objection Certificate from employer", descriptionBn: "নিয়োগকর্তার অনাপত্তি সনদ", isRequired: false },
];

const countries = [
    { name: "Bangladesh", nameBn: "বাংলাদেশ", flag: "🇧🇩", image: "https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Dhaka", capitalBn: "ঢাকা", currency: "BDT", timezone: "GMT+6", touristsPerYear: "1M+", description: "Explore the natural beauty of Bangladesh.", descriptionBn: " can be found in Bangladesh. Explore the flora and fauna of the Sundarbans or relax on the beaches of Cox's Bazar.", startingPrice: 5000, submissionType: "flexible", isFeatured: true, order: 0, visaTypes: [], embassyInfo: { name: "Department of Immigration and Passports", nameBn: "ইমিগ্রেশন ও পাসপোর্ট অধিদপ্তর", address: "Dhaka, Bangladesh", phone: "+880", website: "https://www.passport.gov.bd", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Singapore", nameBn: "সিঙ্গাপুর", flag: "🇸🇬", image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Singapore", capitalBn: "সিঙ্গাপুর", currency: "SGD", timezone: "GMT+8", touristsPerYear: "19.1M", description: "Apply for Singapore visa from Bangladesh. Singapore offers e-visa processing with fast turnaround times.", descriptionBn: "বাংলাদেশ থেকে সিঙ্গাপুর ভিসার জন্য আবেদন করুন।", startingPrice: 6000, submissionType: "e-visa", isFeatured: true, order: 1, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "10-20 Working Days", fee: 6000, governmentFee: 3000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Business Visa", nameBn: "বিজনেস ভিসা", processingTime: "10-20 Working Days", fee: 6000, governmentFee: 3500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Transit Visa", nameBn: "ট্রানজিট ভিসা", processingTime: "10-20 Working Days", fee: 6000, governmentFee: 2000, duration: "4 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 5000, duration: "90 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "High Commission of Singapore", nameBn: "সিঙ্গাপুর হাই কমিশন", address: "House 05, Road 104, Gulshan-2, Dhaka-1212", phone: "+880-2-9881301", website: "https://www.mfa.gov.sg/dhaka", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Malaysia", nameBn: "মালয়েশিয়া", flag: "🇲🇾", image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Kuala Lumpur", capitalBn: "কুয়ালা লামপুর", currency: "MYR", timezone: "GMT+8", touristsPerYear: "26.1M", description: "Malaysia visa from Bangladesh. One of the most popular destinations.", descriptionBn: "বাংলাদেশ থেকে মালয়েশিয়া ভিসা।", startingPrice: 5000, submissionType: "in-person", isFeatured: true, order: 2, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "7-14 Working Days", fee: 5000, governmentFee: 2500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Business Visa", nameBn: "বিজনেস ভিসা", processingTime: "10-15 Working Days", fee: 7000, governmentFee: 3500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Student Visa", nameBn: "স্টুডেন্ট ভিসা", processingTime: "20-30 Working Days", fee: 10000, governmentFee: 5000, duration: "1 Year", entryType: "multiple", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 12000, governmentFee: 6000, duration: "1 Year", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "High Commission of Malaysia", nameBn: "মালয়েশিয়া হাই কমিশন", address: "House 19, Road 6, Baridhara, Dhaka-1212", phone: "+880-2-8822759", website: "https://www.kln.gov.my/web/bgd_dhaka", workingHours: "Sun-Thu 9AM-4:30PM" } },
    { name: "Thailand", nameBn: "থাইল্যান্ড", flag: "🇹🇭", image: "https://images.unsplash.com/photo-1528181304800-259b08848526?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Bangkok", capitalBn: "ব্যাংকক", currency: "THB", timezone: "GMT+7", touristsPerYear: "39.9M", description: "Thailand visa for Bangladeshi citizens.", descriptionBn: "বাংলাদেশি নাগরিকদের জন্য থাইল্যান্ড ভিসা।", startingPrice: 5500, submissionType: "in-person", isFeatured: true, order: 3, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "5-7 Working Days", fee: 5500, governmentFee: 3000, duration: "60 Days", entryType: "single", isAvailable: true }, { name: "Medical Visa", nameBn: "মেডিকেল ভিসা", processingTime: "5-10 Working Days", fee: 5500, governmentFee: 3000, duration: "90 Days", entryType: "single", isAvailable: true }, { name: "Business Visa", nameBn: "বিজনেস ভিসা", processingTime: "7-10 Working Days", fee: 7000, governmentFee: 4500, duration: "90 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Royal Thai Embassy", nameBn: "রয়্যাল থাই দূতাবাস", address: "House 1, Road 51, Gulshan-2, Dhaka-1212", phone: "+880-2-9881866", website: "https://dhaka.thaiembassy.org", workingHours: "Sun-Thu 9:30AM-4:30PM" } },
    { name: "India", nameBn: "ভারত", flag: "🇮🇳", image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "New Delhi", capitalBn: "নতুন দিল্লি", currency: "INR", timezone: "GMT+5:30", touristsPerYear: "17.9M", description: "India visa from Bangladesh. Nearest neighbor with multiple visa options.", descriptionBn: "বাংলাদেশ থেকে ভারত ভিসা।", startingPrice: 1500, submissionType: "flexible", isFeatured: true, order: 4, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "5-7 Working Days", fee: 1500, governmentFee: 1000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Medical Visa", nameBn: "মেডিকেল ভিসা", processingTime: "3-5 Working Days", fee: 2000, governmentFee: 1000, duration: "60 Days", entryType: "multiple", isAvailable: true }, { name: "Business Visa", nameBn: "বিজনেস ভিসা", processingTime: "7-10 Working Days", fee: 3000, governmentFee: 2000, duration: "6 Months", entryType: "multiple", isAvailable: true }, { name: "E-Visa", nameBn: "ই-ভিসা", processingTime: "3-5 Working Days", fee: 2500, governmentFee: 1200, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "High Commission of India", nameBn: "ভারতীয় হাই কমিশন", address: "House 2, Road 142, Gulshan-1, Dhaka-1212", phone: "+880-2-9889339", website: "https://hcidhaka.gov.in", workingHours: "Sun-Thu 9AM-5:30PM" } },
    { name: "United Arab Emirates", nameBn: "সংযুক্ত আরব আমিরাত", flag: "🇦🇪", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=800&auto=format&fit=crop", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Abu Dhabi", capitalBn: "আবু ধাবি", currency: "AED", timezone: "GMT+4", touristsPerYear: "16.7M", description: "UAE visa from Bangladesh. Dubai and Abu Dhabi are top destinations.", descriptionBn: "বাংলাদেশ থেকে ইউএই ভিসা।", startingPrice: 8000, submissionType: "e-visa", isFeatured: true, order: 5, visaTypes: [{ name: "Tourist Visa (30 Days)", nameBn: "ট্যুরিস্ট ভিসা (৩০ দিন)", processingTime: "3-5 Working Days", fee: 8000, governmentFee: 4000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Tourist Visa (90 Days)", nameBn: "ট্যুরিস্ট ভিসা (৯০ দিন)", processingTime: "3-5 Working Days", fee: 15000, governmentFee: 8000, duration: "90 Days", entryType: "multiple", isAvailable: true }, { name: "Transit Visa", nameBn: "ট্রানজিট ভিসা", processingTime: "2-3 Working Days", fee: 5000, governmentFee: 2000, duration: "4 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 20000, governmentFee: 10000, duration: "2 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of UAE", nameBn: "ইউএই দূতাবাস", address: "House NE(K) 4, Road 113, Gulshan-2, Dhaka-1212", phone: "+880-2-8826012", website: "https://www.mofaic.gov.ae", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "Saudi Arabia", nameBn: "সৌদি আরব", flag: "🇸🇦", image: "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?q=80&w=800&auto=format&fit=crop", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Riyadh", capitalBn: "রিয়াদ", currency: "SAR", timezone: "GMT+3", touristsPerYear: "27.4M", description: "Saudi Arabia visa from Bangladesh. Umrah, Hajj, work and tourist visas available.", descriptionBn: "বাংলাদেশ থেকে সৌদি আরব ভিসা।", startingPrice: 10000, submissionType: "flexible", isFeatured: true, order: 6, visaTypes: [{ name: "Tourist E-Visa", nameBn: "ট্যুরিস্ট ই-ভিসা", processingTime: "3-7 Working Days", fee: 10000, governmentFee: 5000, duration: "90 Days", entryType: "multiple", isAvailable: true }, { name: "Umrah Visa", nameBn: "উমরাহ ভিসা", processingTime: "7-14 Working Days", fee: 8000, governmentFee: 3000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "20-45 Working Days", fee: 15000, governmentFee: 8000, duration: "2 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Royal Embassy of Saudi Arabia", nameBn: "সৌদি আরব দূতাবাস", address: "House NW(I)3, Road 74, Gulshan-2, Dhaka-1212", phone: "+880-2-9882700", website: "https://www.saudiembassy.org.bd", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "Turkey", nameBn: "তুরস্ক", flag: "🇹🇷", image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Ankara", capitalBn: "আঙ্কারা", currency: "TRY", timezone: "GMT+3", touristsPerYear: "51.7M", description: "Turkey visa from Bangladesh. E-visa available for tourism.", descriptionBn: "বাংলাদেশ থেকে তুরস্ক ভিসা।", startingPrice: 5000, submissionType: "e-visa", isFeatured: true, order: 7, visaTypes: [{ name: "E-Visa (Tourist)", nameBn: "ই-ভিসা (ট্যুরিস্ট)", processingTime: "3-5 Working Days", fee: 5000, governmentFee: 3500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Sticker Visa", nameBn: "স্টিকার ভিসা", processingTime: "10-20 Working Days", fee: 7000, governmentFee: 5000, duration: "90 Days", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Turkey", nameBn: "তুরস্ক দূতাবাস", address: "House 11, Road 16, Gulshan-1, Dhaka-1212", phone: "+880-2-8833662", website: "https://dhaka.emb.mfa.gov.tr", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "United Kingdom", nameBn: "যুক্তরাজ্য", flag: "🇬🇧", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "London", capitalBn: "লন্ডন", currency: "GBP", timezone: "GMT+0", touristsPerYear: "37.9M", description: "UK visa from Bangladesh. Apply through VFS Global.", descriptionBn: "বাংলাদেশ থেকে যুক্তরাজ্য ভিসা।", startingPrice: 12000, submissionType: "in-person", isFeatured: true, order: 8, visaTypes: [{ name: "Standard Visitor Visa", nameBn: "স্ট্যান্ডার্ড ভিজিটর ভিসা", processingTime: "15-21 Working Days", fee: 12000, governmentFee: 13000, duration: "6 Months", entryType: "multiple", isAvailable: true }, { name: "Student Visa", nameBn: "স্টুডেন্ট ভিসা", processingTime: "21-30 Working Days", fee: 15000, governmentFee: 45000, duration: "Course Duration", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "British High Commission", nameBn: "ব্রিটিশ হাই কমিশন", address: "United Nations Road, Baridhara, Dhaka-1212", phone: "+880-2-8822705", website: "https://www.gov.uk/world/bangladesh", workingHours: "Sun-Thu 8AM-4PM" } },
    { name: "United States", nameBn: "যুক্তরাষ্ট্র", flag: "🇺🇸", image: "https://images.unsplash.com/photo-1485738422979-f5c462d49f04?q=80&w=800&auto=format&fit=crop", region: "North American", regionBn: "উত্তর আমেরিকান", capital: "Washington D.C.", capitalBn: "ওয়াশিংটন ডি.সি.", currency: "USD", timezone: "GMT-5", touristsPerYear: "79.4M", description: "USA visa from Bangladesh. B1/B2 visitor, student and work visas.", descriptionBn: "বাংলাদেশ থেকে আমেরিকা ভিসা।", startingPrice: 15000, submissionType: "in-person", isFeatured: true, order: 9, visaTypes: [{ name: "B1/B2 Visitor Visa", nameBn: "B1/B2 ভিজিটর ভিসা", processingTime: "30-90 Working Days", fee: 15000, governmentFee: 19000, duration: "10 Years", entryType: "multiple", isAvailable: true }, { name: "F1 Student Visa", nameBn: "F1 স্টুডেন্ট ভিসা", processingTime: "30-60 Working Days", fee: 18000, governmentFee: 19000, duration: "Program Duration", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "US Embassy Dhaka", nameBn: "মার্কিন দূতাবাস ঢাকা", address: "Madani Avenue, Baridhara, Dhaka-1212", phone: "+880-2-5566-2000", website: "https://bd.usembassy.gov", workingHours: "Sun-Thu 8AM-4:30PM" } },
    { name: "Canada", nameBn: "কানাডা", flag: "🇨🇦", image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?q=80&w=800&auto=format&fit=crop", region: "North American", regionBn: "উত্তর আমেরিকান", capital: "Ottawa", capitalBn: "অটোয়া", currency: "CAD", timezone: "GMT-5", touristsPerYear: "22.1M", description: "Canada visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে কানাডা ভিসা।", startingPrice: 12000, submissionType: "in-person", isFeatured: true, order: 10, visaTypes: [{ name: "Visitor Visa", nameBn: "ভিজিটর ভিসা", processingTime: "30-60 Working Days", fee: 12000, governmentFee: 10000, duration: "6 Months", entryType: "multiple", isAvailable: true }, { name: "Study Permit", nameBn: "স্টাডি পারমিট", processingTime: "45-90 Working Days", fee: 15000, governmentFee: 18000, duration: "Program Duration", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "High Commission of Canada", nameBn: "কানাডা হাই কমিশন", address: "United Nations Road, Baridhara, Dhaka-1212", phone: "+880-2-9888091", website: "https://www.canada.ca", workingHours: "Sun-Thu 8AM-4:30PM" } },
    { name: "Japan", nameBn: "জাপান", flag: "🇯🇵", image: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Tokyo", capitalBn: "টোকিও", currency: "JPY", timezone: "GMT+9", touristsPerYear: "31.9M", description: "Japan visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে জাপান ভিসা।", startingPrice: 4000, submissionType: "in-person", isFeatured: false, order: 11, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "5-7 Working Days", fee: 4000, governmentFee: 3000, duration: "15 Days", entryType: "single", isAvailable: true }, { name: "Business Visa", nameBn: "বিজনেস ভিসা", processingTime: "5-10 Working Days", fee: 5000, governmentFee: 3000, duration: "90 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of Japan", nameBn: "জাপান দূতাবাস", address: "Plot 5 & 7, Dutabash Road, Baridhara, Dhaka-1212", phone: "+880-2-8810087", website: "https://www.bd.emb-japan.go.jp", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "South Korea", nameBn: "দক্ষিণ কোরিয়া", flag: "🇰🇷", image: "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Seoul", capitalBn: "সিওল", currency: "KRW", timezone: "GMT+9", touristsPerYear: "17.5M", description: "South Korea visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে দক্ষিণ কোরিয়া ভিসা।", startingPrice: 5000, submissionType: "in-person", isFeatured: false, order: 12, visaTypes: [{ name: "Tourist Visa (C-3)", nameBn: "ট্যুরিস্ট ভিসা (C-3)", processingTime: "7-10 Working Days", fee: 5000, governmentFee: 4000, duration: "90 Days", entryType: "single", isAvailable: true }, { name: "Work Visa (E-9)", nameBn: "ওয়ার্ক ভিসা (E-9)", processingTime: "30-60 Working Days", fee: 8000, governmentFee: 7000, duration: "3 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of South Korea", nameBn: "দক্ষিণ কোরিয়া দূতাবাস", address: "4 Madani Avenue, Baridhara, Dhaka-1212", phone: "+880-2-8812088", website: "https://overseas.mofa.go.kr/bd-en", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Qatar", nameBn: "কাতার", flag: "🇶🇦", image: "https://images.unsplash.com/photo-1559564484-e48b3e040ff4?q=80&w=800&auto=format&fit=crop", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Doha", capitalBn: "দোহা", currency: "QAR", timezone: "GMT+3", touristsPerYear: "3.1M", description: "Qatar visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে কাতার ভিসা।", startingPrice: 6000, submissionType: "e-visa", isFeatured: false, order: 13, visaTypes: [{ name: "Tourist Visa", nameBn: "ট্যুরিস্ট ভিসা", processingTime: "5-7 Working Days", fee: 6000, governmentFee: 3500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 12000, governmentFee: 6000, duration: "2 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Qatar", nameBn: "কাতার দূতাবাস", address: "House 44, Road 23, Gulshan-1, Dhaka-1212", phone: "+880-2-9889792", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "Oman", nameBn: "ওমান", flag: "🇴🇲", image: "https://images.unsplash.com/photo-1597220869819-b71a3da8d595?q=80&w=800&auto=format&fit=crop", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Muscat", capitalBn: "মাস্কাট", currency: "OMR", timezone: "GMT+4", touristsPerYear: "3.5M", description: "Oman visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে ওমান ভিসা।", startingPrice: 5000, submissionType: "e-visa", isFeatured: false, order: 14, visaTypes: [{ name: "Tourist E-Visa", nameBn: "ট্যুরিস্ট ই-ভিসা", processingTime: "3-5 Working Days", fee: 5000, governmentFee: 2500, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 10000, governmentFee: 5000, duration: "2 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Oman", nameBn: "ওমান দূতাবাস", address: "Plot 8, Road 112, Gulshan-2, Dhaka-1212", phone: "+880-2-9882245", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "Australia", nameBn: "অস্ট্রেলিয়া", flag: "🇦🇺", image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=800&auto=format&fit=crop", region: "Oceania", regionBn: "ওসেনিয়া", capital: "Canberra", capitalBn: "ক্যানবেরা", currency: "AUD", timezone: "GMT+10", touristsPerYear: "9.5M", description: "Australia visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে অস্ট্রেলিয়া ভিসা।", startingPrice: 12000, submissionType: "in-person", isFeatured: true, order: 15, visaTypes: [{ name: "Visitor Visa (600)", nameBn: "ভিজিটর ভিসা (৬০০)", processingTime: "20-40 Working Days", fee: 12000, governmentFee: 18000, duration: "3-12 Months", entryType: "multiple", isAvailable: true }, { name: "Student Visa (500)", nameBn: "স্টুডেন্ট ভিসা (৫০০)", processingTime: "30-60 Working Days", fee: 15000, governmentFee: 75000, duration: "Course Duration", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Australian High Commission", nameBn: "অস্ট্রেলিয়ান হাই কমিশন", address: "184 Gulshan Avenue, Gulshan-2, Dhaka-1212", phone: "+880-2-8813101", website: "https://bangladesh.highcommission.gov.au", workingHours: "Sun-Thu 8:30AM-4:30PM" } },
    { name: "China", nameBn: "চীন", flag: "🇨🇳", image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Beijing", capitalBn: "বেইজিং", currency: "CNY", timezone: "GMT+8", touristsPerYear: "65.7M", description: "China visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে চীন ভিসা।", startingPrice: 5000, submissionType: "in-person", isFeatured: false, order: 16, visaTypes: [{ name: "Tourist Visa (L)", nameBn: "ট্যুরিস্ট ভিসা (L)", processingTime: "7-10 Working Days", fee: 5000, governmentFee: 4000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Business Visa (M)", nameBn: "বিজনেস ভিসা (M)", processingTime: "7-14 Working Days", fee: 7000, governmentFee: 5000, duration: "60 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of China", nameBn: "চীন দূতাবাস", address: "Plot 2&4, Road 3, Block-I, Baridhara, Dhaka-1212", phone: "+880-2-8824862", website: "https://bd.china-embassy.gov.cn", workingHours: "Sun-Thu 9AM-12PM" } },
    { name: "Vietnam", nameBn: "ভিয়েতনাম", flag: "🇻🇳", image: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Hanoi", capitalBn: "হ্যানয়", currency: "VND", timezone: "GMT+7", touristsPerYear: "18M", description: "Vietnam visa from Bangladesh. E-visa available.", descriptionBn: "বাংলাদেশ থেকে ভিয়েতনাম ভিসা।", startingPrice: 3000, submissionType: "e-visa", isFeatured: false, order: 17, visaTypes: [{ name: "Tourist E-Visa", nameBn: "ট্যুরিস্ট ই-ভিসা", processingTime: "3-5 Working Days", fee: 3000, governmentFee: 2500, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of Vietnam", nameBn: "ভিয়েতনাম দূতাবাস", address: "House 1, Road 59, Gulshan-2, Dhaka-1212", phone: "+880-2-9882529", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Indonesia", nameBn: "ইন্দোনেশিয়া", flag: "🇮🇩", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Jakarta", capitalBn: "জাকার্তা", currency: "IDR", timezone: "GMT+7", touristsPerYear: "16.1M", description: "Indonesia visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে ইন্দোনেশিয়া ভিসা।", startingPrice: 4000, submissionType: "e-visa", isFeatured: false, order: 18, visaTypes: [{ name: "Tourist Visa on Arrival", nameBn: "ভিসা অন অ্যারাইভাল", processingTime: "Instant", fee: 4000, governmentFee: 3500, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of Indonesia", nameBn: "ইন্দোনেশিয়া দূতাবাস", address: "House CWN(C)6A, Road 48, Gulshan-2, Dhaka-1212", phone: "+880-2-9880795", workingHours: "Sun-Thu 9AM-4PM" } },
    { name: "Sri Lanka", nameBn: "শ্রীলঙ্কা", flag: "🇱🇰", image: "https://images.unsplash.com/photo-1586003903385-28a5c81d84d0?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Colombo", capitalBn: "কলম্বো", currency: "LKR", timezone: "GMT+5:30", touristsPerYear: "2.3M", description: "Sri Lanka visa from Bangladesh. ETA available.", descriptionBn: "বাংলাদেশ থেকে শ্রীলঙ্কা ভিসা।", startingPrice: 3000, submissionType: "e-visa", isFeatured: false, order: 19, visaTypes: [{ name: "ETA Tourist Visa", nameBn: "ইটিএ ট্যুরিস্ট ভিসা", processingTime: "1-3 Working Days", fee: 3000, governmentFee: 2000, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "High Commission of Sri Lanka", nameBn: "শ্রীলঙ্কা হাই কমিশন", address: "House 15, Road 118, Gulshan-1, Dhaka-1212", phone: "+880-2-8826397", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Maldives", nameBn: "মালদ্বীপ", flag: "🇲🇻", image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800&auto=format&fit=crop", region: "Asian", regionBn: "এশিয়ান", capital: "Male", capitalBn: "মালে", currency: "MVR", timezone: "GMT+5", touristsPerYear: "1.9M", description: "Maldives visa from Bangladesh. Free visa on arrival for 30 days.", descriptionBn: "বাংলাদেশ থেকে মালদ্বীপ ভিসা। ৩০ দিনের ফ্রি ভিসা অন অ্যারাইভাল।", startingPrice: 0, submissionType: "e-visa", isFeatured: false, order: 20, visaTypes: [{ name: "Visa on Arrival (Free)", nameBn: "ফ্রি ভিসা অন অ্যারাইভাল", processingTime: "Instant", fee: 0, governmentFee: 0, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "High Commission of Maldives", nameBn: "মালদ্বীপ হাই কমিশন", address: "House NW(I)5, Road 74, Gulshan-2, Dhaka-1212", phone: "+880-2-9887171", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "France", nameBn: "ফ্রান্স", flag: "🇫🇷", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Paris", capitalBn: "প্যারিস", currency: "EUR", timezone: "GMT+1", touristsPerYear: "89.4M", description: "France Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে ফ্রান্স শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 21, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }, { name: "Student Visa", nameBn: "স্টুডেন্ট ভিসা", processingTime: "30-45 Working Days", fee: 10000, governmentFee: 12000, duration: "1 Year", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of France", nameBn: "ফ্রান্স দূতাবাস", address: "House 18, Road 108, Gulshan-2, Dhaka-1212", phone: "+880-2-8813811", website: "https://bd.ambafrance.org", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Germany", nameBn: "জার্মানি", flag: "🇩🇪", image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Berlin", capitalBn: "বার্লিন", currency: "EUR", timezone: "GMT+1", touristsPerYear: "39.6M", description: "Germany Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে জার্মানি শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 22, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }, { name: "Student Visa", nameBn: "স্টুডেন্ট ভিসা", processingTime: "30-60 Working Days", fee: 10000, governmentFee: 8000, duration: "1 Year", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "German Embassy", nameBn: "জার্মান দূতাবাস", address: "178 Gulshan Avenue, Gulshan-2, Dhaka-1212", phone: "+880-2-8853521", website: "https://dhaka.diplo.de", workingHours: "Sun-Thu 8:30AM-4:30PM" } },
    { name: "Italy", nameBn: "ইতালি", flag: "🇮🇹", image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Rome", capitalBn: "রোম", currency: "EUR", timezone: "GMT+1", touristsPerYear: "64.5M", description: "Italy Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে ইতালি শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 23, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Italy", nameBn: "ইতালি দূতাবাস", address: "Plot 2/3, Road 74/79, Gulshan-2, Dhaka-1212", phone: "+880-2-8822781", website: "https://ambdhaka.esteri.it", workingHours: "Sun-Thu 8:30AM-4:30PM" } },
    { name: "Spain", nameBn: "স্পেন", flag: "🇪🇸", image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Madrid", capitalBn: "মাদ্রিদ", currency: "EUR", timezone: "GMT+1", touristsPerYear: "83.7M", description: "Spain Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে স্পেন শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 24, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Spain", nameBn: "স্পেন দূতাবাস", address: "House 9, Road 16, Gulshan-1, Dhaka-1212", workingHours: "Sun-Thu 9AM-5PM" } },
    { name: "Switzerland", nameBn: "সুইজারল্যান্ড", flag: "🇨🇭", image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Bern", capitalBn: "বার্ন", currency: "CHF", timezone: "GMT+1", touristsPerYear: "11.7M", description: "Switzerland Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে সুইজারল্যান্ড শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 25, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Switzerland", nameBn: "সুইজারল্যান্ড দূতাবাস", address: "House 2, Road 56, Gulshan-2, Dhaka-1212", phone: "+880-2-8826734", website: "https://www.eda.admin.ch/dhaka", workingHours: "Sun-Thu 9AM-12PM" } },
    { name: "Netherlands", nameBn: "নেদারল্যান্ডস", flag: "🇳🇱", image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?q=80&w=800&auto=format&fit=crop", region: "European", regionBn: "ইউরোপীয়", capital: "Amsterdam", capitalBn: "আমস্টারডাম", currency: "EUR", timezone: "GMT+1", touristsPerYear: "20.1M", description: "Netherlands Schengen visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে নেদারল্যান্ডস শেনজেন ভিসা।", startingPrice: 8000, submissionType: "in-person", isFeatured: false, order: 26, visaTypes: [{ name: "Schengen Tourist Visa", nameBn: "শেনজেন ট্যুরিস্ট ভিসা", processingTime: "15-30 Working Days", fee: 8000, governmentFee: 10000, duration: "90 Days", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Netherlands", nameBn: "নেদারল্যান্ডস দূতাবাস", address: "House 49, Road 90, Gulshan-2, Dhaka-1212", phone: "+880-2-8822715", website: "https://www.netherlandsworldwide.nl/countries/bangladesh", workingHours: "Sun-Thu 8:30AM-5PM" } },
    { name: "Kuwait", nameBn: "কুয়েত", flag: "🇰🇼", image: "https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?q=80&w=800&auto=format&fit=crop", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Kuwait City", capitalBn: "কুয়েত সিটি", currency: "KWD", timezone: "GMT+3", touristsPerYear: "8.3M", description: "Kuwait visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে কুয়েত ভিসা।", startingPrice: 7000, submissionType: "in-person", isFeatured: false, order: 27, visaTypes: [{ name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 10000, governmentFee: 5000, duration: "2 Years", entryType: "multiple", isAvailable: true }, { name: "Family Visit Visa", nameBn: "ফ্যামিলি ভিজিট ভিসা", processingTime: "7-14 Working Days", fee: 7000, governmentFee: 4000, duration: "90 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of Kuwait", nameBn: "কুয়েত দূতাবাস", address: "House 10, Road 50, Gulshan-2, Dhaka-1212", phone: "+880-2-9885085", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "Bahrain", nameBn: "বাহরাইন", flag: "🇧🇭", image: "https://cdn.pixabay.com/photo/2020/01/31/07/26/bahrain-4807624_1280.jpg", region: "Middle Eastern", regionBn: "মধ্যপ্রাচ্য", capital: "Manama", capitalBn: "মানামা", currency: "BHD", timezone: "GMT+3", touristsPerYear: "4.4M", description: "Bahrain visa from Bangladesh. E-visa available.", descriptionBn: "বাংলাদেশ থেকে বাহরাইন ভিসা।", startingPrice: 5000, submissionType: "e-visa", isFeatured: false, order: 28, visaTypes: [{ name: "Tourist E-Visa", nameBn: "ট্যুরিস্ট ই-ভিসা", processingTime: "3-5 Working Days", fee: 5000, governmentFee: 3000, duration: "30 Days", entryType: "single", isAvailable: true }, { name: "Work Visa", nameBn: "ওয়ার্ক ভিসা", processingTime: "15-30 Working Days", fee: 10000, governmentFee: 5000, duration: "2 Years", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "Embassy of Bahrain", nameBn: "বাহরাইন দূতাবাস", address: "House CWN(C)6, Road 34, Gulshan-2, Dhaka-1212", phone: "+880-2-9893032", workingHours: "Sun-Thu 9AM-3PM" } },
    { name: "New Zealand", nameBn: "নিউজিল্যান্ড", flag: "🇳🇿", image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?q=80&w=800&auto=format&fit=crop", region: "Oceania", regionBn: "ওসেনিয়া", capital: "Wellington", capitalBn: "ওয়েলিংটন", currency: "NZD", timezone: "GMT+12", touristsPerYear: "3.9M", description: "New Zealand visa from Bangladesh.", descriptionBn: "বাংলাদেশ থেকে নিউজিল্যান্ড ভিসা।", startingPrice: 12000, submissionType: "in-person", isFeatured: false, order: 29, visaTypes: [{ name: "Visitor Visa", nameBn: "ভিজিটর ভিসা", processingTime: "20-40 Working Days", fee: 12000, governmentFee: 15000, duration: "9 Months", entryType: "multiple", isAvailable: true }, { name: "Student Visa", nameBn: "স্টুডেন্ট ভিসা", processingTime: "30-60 Working Days", fee: 15000, governmentFee: 25000, duration: "Course Duration", entryType: "multiple", isAvailable: true }], embassyInfo: { name: "New Zealand High Commission (via Bangkok)", nameBn: "নিউজিল্যান্ড হাই কমিশন (ব্যাংকক)", address: "Apply via VFS Global or Bangkok Embassy", workingHours: "Online Application" } },
    { name: "Egypt", nameBn: "মিশর", flag: "🇪🇬", image: "https://cdn.pixabay.com/photo/2015/11/01/23/30/pyramids-1017499_1280.jpg", region: "African", regionBn: "আফ্রিকান", capital: "Cairo", capitalBn: "কায়রো", currency: "EGP", timezone: "GMT+2", touristsPerYear: "13.1M", description: "Egypt visa from Bangladesh. E-visa available.", descriptionBn: "বাংলাদেশ থেকে মিশর ভিসা।", startingPrice: 4000, submissionType: "e-visa", isFeatured: false, order: 30, visaTypes: [{ name: "Tourist E-Visa", nameBn: "ট্যুরিস্ট ই-ভিসা", processingTime: "5-7 Working Days", fee: 4000, governmentFee: 3000, duration: "30 Days", entryType: "single", isAvailable: true }], embassyInfo: { name: "Embassy of Egypt", nameBn: "মিশর দূতাবাস", address: "House NE(N)4, Road 90, Gulshan-2, Dhaka-1212", phone: "+880-2-9884517", workingHours: "Sun-Thu 9AM-3PM" } },
];

countries.forEach(c => { c.documentRequirements = commonDocs; c.isActive = true; });

async function seed() {
    // Login first
    console.log("🔐 Logging in...");
    let token;
    try {
        const loginRes = await fetch(`${API}/api/auth/login`, {
            method: "POST", headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ email: "admin@gmail.com", password: "admin@gmail.com" })
        });
        const loginData = await loginRes.json();
        token = loginData?.data?.tokens?.accessToken || loginData?.data?.token || loginData?.token;
        if (!token) { console.log("❌ Login failed:", JSON.stringify(loginData)); return; }
        console.log("✅ Logged in!\n");
    } catch (e) { console.log("❌ Login error:", e.message); return; }

    console.log(`🌍 Seeding ${countries.length} countries...\n`);
    let ok = 0, fail = 0;
    for (const c of countries) {
        try {
            const res = await fetch(`${API}/api/countries`, {
                method: "POST",
                headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
                body: JSON.stringify(c)
            });
            const d = await res.json();
            if (d.success) { ok++; console.log(`  ✅ ${c.flag} ${c.name}`); }
            else { fail++; console.log(`  ❌ ${c.name}: ${d.message || JSON.stringify(d)}`); }
        } catch (e) { fail++; console.log(`  ❌ ${c.name}: ${e.message}`); }
    }
    console.log(`\n🎉 Done! ${ok} added, ${fail} failed.\n`);
}
seed();
