const { MongoClient } = require("mongodb");
const uri = "mongodb+srv://visaprobd:visaprobd@cluster0.b5kfivm.mongodb.net/visaprobd?appName=Cluster0";

const hotels = [
    // ===== Bangladesh Hotels =====
    {
        name: "The Westin Dhaka",
        nameBn: "দ্য ওয়েস্টিন ঢাকা",
        slug: "the-westin-dhaka",
        image: "https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Main Gulshan Ave, Gulshan 1, Dhaka 1212",
        locationBn: "মেইন গুলশান অ্যাভিনিউ, গুলশান ১, ঢাকা ১২১২",
        city: "Dhaka",
        cityBn: "ঢাকা",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Deluxe Room",
        roomTypeBn: "ডিলাক্স রুম",
        pricePerNight: 18500,
        oldPrice: 22000,
        currency: "BDT",
        totalRooms: 220,
        availableRooms: 45,
        checkInTime: "14:00",
        checkOutTime: "12:00",
        amenities: ["Free WiFi", "Swimming Pool", "Spa & Wellness", "Fitness Center", "Restaurant", "Room Service", "Airport Shuttle", "Business Center", "Valet Parking", "Concierge"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "সুইমিং পুল", "স্পা ও ওয়েলনেস", "ফিটনেস সেন্টার", "রেস্তোরাঁ", "রুম সার্ভিস", "এয়ারপোর্ট শাটল", "বিজনেস সেন্টার", "ভ্যালেট পার্কিং", "কনসিয়ার্জ"],
        description: "Experience world-class luxury at The Westin Dhaka, located in the prestigious Gulshan area. Featuring Heavenly Beds and Westin Wellness amenities.",
        descriptionBn: "মর্যাদাপূর্ণ গুলশান এলাকায় অবস্থিত দ্য ওয়েস্টিন ঢাকায় বিশ্বমানের বিলাসিতা উপভোগ করুন।",
        longDescription: "The Westin Dhaka is the city's premier luxury hotel, situated in the heart of Gulshan diplomatic zone. Featuring 220 elegantly appointed rooms and suites, the hotel offers an unparalleled experience with its signature Heavenly Bed, WestinWORKOUT Fitness Studio, and rejuvenating Heavenly Spa. The Seasonal Tastes restaurant offers international buffet cuisine, while the Pool Bar provides a relaxing atmosphere. Ideal for both business and leisure travelers.",
        longDescriptionBn: "দ্য ওয়েস্টিন ঢাকা শহরের প্রিমিয়ার লাক্সারি হোটেল, গুলশান কূটনৈতিক এলাকার কেন্দ্রে অবস্থিত। ২২০টি সুদৃশ্য কক্ষ ও স্যুট সমেত এই হোটেলে হেভেনলি বেড, ওয়েস্টিনওয়ার্কআউট ফিটনেস স্টুডিও এবং হেভেনলি স্পা রয়েছে।",
        faqs: [
            { question: "Is airport transfer available?", questionBn: "এয়ারপোর্ট ট্রান্সফার কি পাওয়া যায়?", answer: "Yes, airport transfers are available on request.", answerBn: "হ্যাঁ, অনুরোধে এয়ারপোর্ট ট্রান্সফার পাওয়া যায়।" },
            { question: "Is breakfast included?", questionBn: "কি ব্রেকফাস্ট অন্তর্ভুক্ত?", answer: "Breakfast is available as an add-on package.", answerBn: "ব্রেকফাস্ট অ্যাড-অন প্যাকেজ হিসেবে পাওয়া যায়।" },
        ],
        tags: ["Luxury", "Business", "Gulshan", "5-Star", "Spa"],
        rating: 4.8,
        reviewsCount: 1240,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 1,
    },
    {
        name: "Cox's Bazar Sayeman Beach Resort",
        nameBn: "কক্সবাজার সায়েমান বিচ রিসোর্ট",
        slug: "coxs-bazar-sayeman-beach-resort",
        image: "https://images.pexels.com/photos/1371360/pexels-photo-1371360.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/2373202/pexels-photo-2373202.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/261169/pexels-photo-261169.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Kolatoli Sea Beach Road, Cox's Bazar 4700",
        locationBn: "কোলাতলী সি বিচ রোড, কক্সবাজার ৪৭০০",
        city: "Cox's Bazar",
        cityBn: "কক্সবাজার",
        starRating: 5,
        hotelCategory: "resort",
        roomType: "Sea View Suite",
        roomTypeBn: "সি ভিউ স্যুট",
        pricePerNight: 14000,
        oldPrice: 18000,
        currency: "BDT",
        totalRooms: 160,
        availableRooms: 32,
        checkInTime: "14:00",
        checkOutTime: "11:00",
        amenities: ["Sea View Rooms", "Private Beach", "Rooftop Pool", "Seafood Restaurant", "Free WiFi", "Spa", "Kids Club", "Water Sports"],
        amenitiesBn: ["সি ভিউ রুম", "প্রাইভেট বিচ", "রুফটপ পুল", "সীফুড রেস্তোরাঁ", "বিনামূল্যে ওয়াইফাই", "স্পা", "কিডস ক্লাব", "ওয়াটার স্পোর্টস"],
        description: "Wake up to breathtaking ocean views at Sayeman Beach Resort, perched right on Cox's Bazar's world-famous shoreline.",
        descriptionBn: "বিশ্বখ্যাত কক্সবাজার সমুদ্র সৈকতে অবস্থিত সায়েমান বিচ রিসোর্টে অসাধারণ সমুদ্রের দৃশ্য দিয়ে ঘুম থেকে উঠুন।",
        longDescription: "Sayeman Beach Resort is Cox's Bazar's most iconic beachfront property, offering panoramic views of the Bay of Bengal. The resort features 160 elegantly designed rooms, a rooftop infinity pool, private beach access, and the renowned Rong Cafe. Enjoy fresh seafood, water sports, and spa treatments. Perfect for families, couples, and honeymooners seeking an unforgettable coastal escape.",
        longDescriptionBn: "সায়েমান বিচ রিসোর্ট কক্সবাজারের সবচেয়ে আইকনিক বিচফ্রন্ট প্রপার্টি, বঙ্গোপসাগরের প্যানোরামিক দৃশ্য সহ। রিসোর্টে ১৬০টি সুদৃশ্য রুম, রুফটপ ইনফিনিটি পুল, প্রাইভেট বিচ অ্যাক্সেস রয়েছে।",
        faqs: [
            { question: "Is the beach private?", questionBn: "বিচটি কি প্রাইভেট?", answer: "The resort has a designated private beach area for guests.", answerBn: "রিসোর্টের গেস্টদের জন্য নির্ধারিত প্রাইভেট বিচ এলাকা আছে।" },
            { question: "Are water sports available?", questionBn: "ওয়াটার স্পোর্টস কি পাওয়া যায়?", answer: "Yes, jet skiing, parasailing, and beach volleyball are available.", answerBn: "হ্যাঁ, জেট স্কিইং, প্যারাসেইলিং এবং বিচ ভলিবল পাওয়া যায়।" },
        ],
        tags: ["Beach", "Resort", "Sea View", "Honeymoon", "Family"],
        rating: 4.7,
        reviewsCount: 890,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 2,
    },
    {
        name: "Pan Pacific Sonargaon Dhaka",
        nameBn: "প্যান প্যাসিফিক সোনারগাঁও ঢাকা",
        slug: "pan-pacific-sonargaon-dhaka",
        image: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "107 Kazi Nazrul Islam Avenue, Karwan Bazar, Dhaka 1215",
        locationBn: "১০৭ কাজী নজরুল ইসলাম অ্যাভিনিউ, কারওয়ান বাজার, ঢাকা ১২১৫",
        city: "Dhaka",
        cityBn: "ঢাকা",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Superior Room",
        roomTypeBn: "সুপেরিয়র রুম",
        pricePerNight: 16500,
        oldPrice: 20000,
        currency: "BDT",
        totalRooms: 280,
        availableRooms: 60,
        checkInTime: "15:00",
        checkOutTime: "12:00",
        amenities: ["Free WiFi", "Outdoor Pool", "Health Club", "Multiple Restaurants", "Shopping Arcade", "Business Center", "Banquet Halls", "Valet Parking"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "আউটডোর পুল", "হেলথ ক্লাব", "একাধিক রেস্তোরাঁ", "শপিং আর্কেড", "বিজনেস সেন্টার", "ব্যাংকোয়েট হল", "ভ্যালেট পার্কিং"],
        description: "Dhaka's landmark luxury hotel since 1981, Pan Pacific Sonargaon is centrally located near parliament and embassies.",
        descriptionBn: "১৯৮১ সাল থেকে ঢাকার ল্যান্ডমার্ক লাক্সারি হোটেল, প্যান প্যাসিফিক সোনারগাঁও সংসদ ও দূতাবাসের কাছে কেন্দ্রীয়ভাবে অবস্থিত।",
        longDescription: "Pan Pacific Sonargaon Dhaka has been the city's most distinguished address since 1981. Situated in the heart of Dhaka, this iconic hotel features 280 luxuriously appointed rooms and suites. Dining options include Café Bazar for international cuisine, Jharna for authentic Bangladeshi dishes, and Lobby Lounge for afternoon tea. The hotel is the preferred choice for heads of state, diplomats, and discerning business travelers.",
        longDescriptionBn: "প্যান প্যাসিফিক সোনারগাঁও ঢাকা ১৯৮১ সাল থেকে শহরের সবচেয়ে মর্যাদাপূর্ণ ঠিকানা। ঢাকার কেন্দ্রে অবস্থিত এই আইকনিক হোটেলে ২৮০টি লাক্সারি রুম ও স্যুট রয়েছে।",
        faqs: [
            { question: "Is the hotel near Hazrat Shahjalal Airport?", questionBn: "হোটেলটি কি হযরত শাহজালাল বিমানবন্দরের কাছে?", answer: "The hotel is about 20 km from the airport, approximately 45 minutes by car.", answerBn: "হোটেলটি বিমানবন্দর থেকে প্রায় ২০ কিমি, গাড়িতে প্রায় ৪৫ মিনিট।" },
        ],
        tags: ["Luxury", "Iconic", "Business", "Diplomatic", "Central"],
        rating: 4.6,
        reviewsCount: 1560,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 3,
    },
    {
        name: "Long Beach Hotel Sylhet",
        nameBn: "লং বিচ হোটেল সিলেট",
        slug: "long-beach-hotel-sylhet",
        image: "https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Airport Road, Sylhet 3100",
        locationBn: "এয়ারপোর্ট রোড, সিলেট ৩১০০",
        city: "Sylhet",
        cityBn: "সিলেট",
        starRating: 4,
        hotelCategory: "business",
        roomType: "Deluxe Double Room",
        roomTypeBn: "ডিলাক্স ডাবল রুম",
        pricePerNight: 7500,
        oldPrice: 9500,
        currency: "BDT",
        totalRooms: 120,
        availableRooms: 28,
        checkInTime: "14:00",
        checkOutTime: "12:00",
        amenities: ["Free WiFi", "Rooftop Restaurant", "Banquet Hall", "Parking", "Room Service", "Laundry", "Travel Desk", "Bar"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "রুফটপ রেস্তোরাঁ", "ব্যাংকোয়েট হল", "পার্কিং", "রুম সার্ভিস", "লন্ড্রি", "ট্রাভেল ডেস্ক", "বার"],
        description: "Sylhet's premier business hotel with stunning views of tea gardens and easy access to Ratargul Swamp Forest.",
        descriptionBn: "সিলেটের প্রিমিয়ার বিজনেস হোটেল, চা বাগানের অপরূপ দৃশ্য এবং রাতারগুল বনের সহজ প্রবেশাধিকার সহ।",
        longDescription: "Long Beach Hotel Sylhet is the city's top-rated 4-star property, perfectly located near the airport and Osmani Cricket Stadium. The hotel offers 120 well-appointed rooms with modern amenities. The rooftop restaurant serves authentic Sylheti cuisine and international dishes with panoramic views. Ideal for exploring Ratargul Swamp Forest, Jaflong, Bisnakandi, and the famous tea estates of Sylhet.",
        longDescriptionBn: "লং বিচ হোটেল সিলেট শহরের সর্বোচ্চ রেটেড ৪-তারা প্রপার্টি, বিমানবন্দর ও ওসমানী ক্রিকেট স্টেডিয়ামের কাছে।",
        faqs: [
            { question: "Is Ratargul Swamp accessible from the hotel?", questionBn: "হোটেল থেকে রাতারগুল বন কি সহজে যাওয়া যায়?", answer: "Yes, Ratargul is about 26 km away, our travel desk can arrange transport.", answerBn: "হ্যাঁ, রাতারগুল প্রায় ২৬ কিমি দূরে, আমাদের ট্রাভেল ডেস্ক পরিবহন ব্যবস্থা করতে পারে।" },
        ],
        tags: ["Tea Garden", "Business", "Sylhet", "4-Star", "Airport"],
        rating: 4.4,
        reviewsCount: 423,
        status: "active",
        isActive: true,
        isFeatured: false,
        order: 4,
    },
    {
        name: "Hotel Sea Palace Cox's Bazar",
        nameBn: "হোটেল সী প্যালেস কক্সবাজার",
        slug: "hotel-sea-palace-coxs-bazar",
        image: "https://images.pexels.com/photos/261187/pexels-photo-261187.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/2869215/pexels-photo-2869215.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1579253/pexels-photo-1579253.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Hotel Motel Zone, Cox's Bazar 4700",
        locationBn: "হোটেল মোটেল জোন, কক্সবাজার ৪৭০০",
        city: "Cox's Bazar",
        cityBn: "কক্সবাজার",
        starRating: 3,
        hotelCategory: "mid-range",
        roomType: "Standard Sea View",
        roomTypeBn: "স্ট্যান্ডার্ড সি ভিউ",
        pricePerNight: 4500,
        oldPrice: 6000,
        currency: "BDT",
        totalRooms: 85,
        availableRooms: 20,
        checkInTime: "12:00",
        checkOutTime: "11:00",
        amenities: ["Free WiFi", "Sea View Balcony", "Restaurant", "24/7 Room Service", "Parking", "Laundry Service"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "সি ভিউ বালকনি", "রেস্তোরাঁ", "২৪/৭ রুম সার্ভিস", "পার্কিং", "লন্ড্রি সার্ভিস"],
        description: "Affordable beachfront accommodation with stunning sea views, perfect for budget-conscious travelers who don't want to compromise on location.",
        descriptionBn: "বাজেট সচেতন পর্যটকদের জন্য সাশ্রয়ী বিচফ্রন্ট আবাসন, অসাধারণ সমুদ্র দৃশ্য সহ।",
        longDescription: "Hotel Sea Palace offers excellent value for money in the heart of Cox's Bazar Hotel Zone. All 85 rooms feature balconies with sea views, air conditioning, and modern bathrooms. The rooftop restaurant serves fresh seafood and Bengali cuisine. Just 2 minutes walk to the beach, the hotel is ideal for families and couples seeking a comfortable beach holiday without breaking the bank.",
        longDescriptionBn: "হোটেল সী প্যালেস কক্সবাজার হোটেল জোনে চমৎকার মানের সুবিধা দেয়। সব ৮৫টি রুমে সি ভিউ সহ বালকনি, এসি এবং আধুনিক বাথরুম রয়েছে।",
        faqs: [
            { question: "How far is the beach?", questionBn: "বিচ কতটুকু দূরে?", answer: "The hotel is just a 2-minute walk from the main beach.", answerBn: "হোটেলটি মূল বিচ থেকে মাত্র ২ মিনিটের হাঁটার পথে।" },
        ],
        tags: ["Budget Friendly", "Sea View", "Beach", "Family"],
        rating: 4.2,
        reviewsCount: 678,
        status: "active",
        isActive: true,
        isFeatured: false,
        order: 5,
    },

    // ===== International Hotels =====
    {
        name: "Burj Al Arab Jumeirah Dubai",
        nameBn: "বুর্জ আল আরব জুমেইরাহ দুবাই",
        slug: "burj-al-arab-jumeirah-dubai",
        image: "https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1838554/pexels-photo-1838554.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Jumeirah Beach Road, Jumeirah, Dubai, UAE",
        locationBn: "জুমেইরাহ বিচ রোড, জুমেইরাহ, দুবাই, ইউএই",
        city: "Dubai",
        cityBn: "দুবাই",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Panoramic Suite",
        roomTypeBn: "প্যানোরামিক স্যুট",
        pricePerNight: 95000,
        oldPrice: 120000,
        currency: "BDT",
        totalRooms: 202,
        availableRooms: 15,
        checkInTime: "15:00",
        checkOutTime: "12:00",
        amenities: ["Private Butler", "Helipad", "Underwater Restaurant", "Private Beach", "Rolls Royce Transfer", "Gold-plated iPad", "Infinity Pool", "Spa", "Tennis Court", "Water Sports"],
        amenitiesBn: ["প্রাইভেট বাটলার", "হেলিপ্যাড", "আন্ডারওয়াটার রেস্তোরাঁ", "প্রাইভেট বিচ", "রোলস রয়েস ট্রান্সফার", "গোল্ড আইপ্যাড", "ইনফিনিটি পুল", "স্পা", "টেনিস কোর্ট", "ওয়াটার স্পোর্টস"],
        description: "The world's most luxurious hotel, standing on its own island shaped like a sail. An icon of Dubai and the ultimate in ultra-luxury hospitality.",
        descriptionBn: "বিশ্বের সবচেয়ে বিলাসবহুল হোটেল, পাল আকৃতির নিজস্ব দ্বীপে দাঁড়িয়ে। দুবাইয়ের আইকন এবং আলট্রা-লাক্সারি আতিথেয়তার চূড়ান্ত।",
        longDescription: "Burj Al Arab Jumeirah is the world's most recognizable hotel, designed to resemble a billowing sail. All 202 suites are duplex with stunning views of the Arabian Gulf or Dubai skyline. Guests enjoy personalized butler service, transfer by Rolls Royce or private helicopter, and access to 9 world-class restaurants including the underwater Al Mahara. The hotel represents the pinnacle of luxury for the discerning traveler.",
        longDescriptionBn: "বুর্জ আল আরব জুমেইরাহ বিশ্বের সবচেয়ে পরিচিত হোটেল, পালের মতো দেখতে ডিজাইন করা হয়েছে। সব ২০২টি স্যুট ডুপ্লেক্স, আরব উপসাগর বা দুবাই স্কাইলাইনের দৃষ্টিনন্দন দৃশ্য সহ।",
        faqs: [
            { question: "Do you need to be a guest to visit?", questionBn: "ভিজিট করতে কি গেস্ট হতে হবে?", answer: "Yes, entry to Burj Al Arab is by reservation only for dining or staying.", answerBn: "হ্যাঁ, বুর্জ আল আরবে প্রবেশ শুধুমাত্র ডাইনিং বা থাকার রিজার্ভেশনের মাধ্যমে।" },
        ],
        tags: ["Ultra Luxury", "Dubai", "Iconic", "7-Star", "Sea View"],
        rating: 4.9,
        reviewsCount: 3420,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 6,
    },
    {
        name: "Raffles Hotel Singapore",
        nameBn: "র‍্যাফেলস হোটেল সিঙ্গাপুর",
        slug: "raffles-hotel-singapore",
        image: "https://images.pexels.com/photos/2034335/pexels-photo-2034335.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/261395/pexels-photo-261395.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "1 Beach Road, Singapore 189673",
        locationBn: "১ বিচ রোড, সিঙ্গাপুর ১৮৯৬৭৩",
        city: "Singapore",
        cityBn: "সিঙ্গাপুর",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Palm Court Suite",
        roomTypeBn: "পাম কোর্ট স্যুট",
        pricePerNight: 72000,
        oldPrice: 90000,
        currency: "BDT",
        totalRooms: 115,
        availableRooms: 20,
        checkInTime: "15:00",
        checkOutTime: "12:00",
        amenities: ["Free WiFi", "Outdoor Pool", "Spa", "6 Restaurants & Bars", "Butler Service", "Shopping Arcade", "Fitness Center", "Colonial Architecture"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "আউটডোর পুল", "স্পা", "৬টি রেস্তোরাঁ ও বার", "বাটলার সার্ভিস", "শপিং আর্কেড", "ফিটনেস সেন্টার", "কলোনিয়াল আর্কিটেকচার"],
        description: "A legendary colonial-era grand dame, Raffles Singapore has welcomed kings, presidents, and celebrities since 1887. Home of the iconic Singapore Sling cocktail.",
        descriptionBn: "১৮৮৭ সাল থেকে রাজা, রাষ্ট্রপতি ও সেলিব্রিটিদের আতিথ্য করে আসছে। আইকনিক সিঙ্গাপুর স্লিং ককটেলের জন্মস্থান।",
        longDescription: "Raffles Hotel Singapore is an institution. Established in 1887, this National Monument and Singapore icon has been hosting luminaries for over a century. The hotel features 115 luxurious suites, each reflecting the colonial heritage with modern comforts. Dine at the legendary Long Bar — birthplace of the Singapore Sling — or enjoy fine dining at BBR by Alain Ducasse. A truly timeless experience in the heart of Singapore.",
        longDescriptionBn: "র‍্যাফেলস হোটেল সিঙ্গাপুর একটি প্রতিষ্ঠান। ১৮৮৭ সালে প্রতিষ্ঠিত এই জাতীয় স্মারক শতাব্দীরও বেশি সময় ধরে বিখ্যাত ব্যক্তিদের আতিথ্য করে আসছে।",
        faqs: [
            { question: "Can non-guests dine at Raffles?", questionBn: "নন-গেস্টরা কি র‍্যাফেলসে খেতে পারেন?", answer: "Yes, the Long Bar, restaurants and arcade shops are open to the public.", answerBn: "হ্যাঁ, লং বার, রেস্তোরাঁ এবং আর্কেড শপ জনসাধারণের জন্য খোলা।" },
        ],
        tags: ["Historic", "Luxury", "Singapore", "Colonial", "Iconic"],
        rating: 4.8,
        reviewsCount: 2890,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 7,
    },
    {
        name: "Mandarin Oriental Kuala Lumpur",
        nameBn: "ম্যান্ডারিন ওরিয়েন্টাল কুয়ালালামপুর",
        slug: "mandarin-oriental-kuala-lumpur",
        image: "https://images.pexels.com/photos/2096983/pexels-photo-2096983.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/2029698/pexels-photo-2029698.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1838554/pexels-photo-1838554.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Kuala Lumpur City Centre, Kuala Lumpur 50088, Malaysia",
        locationBn: "কুয়ালালামপুর সিটি সেন্টার, কুয়ালালামপুর ৫০০৮৮, মালয়েশিয়া",
        city: "Kuala Lumpur",
        cityBn: "কুয়ালালামপুর",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Deluxe Twin Petronas View",
        roomTypeBn: "ডিলাক্স টুইন পেট্রোনাস ভিউ",
        pricePerNight: 32000,
        oldPrice: 40000,
        currency: "BDT",
        totalRooms: 643,
        availableRooms: 85,
        checkInTime: "15:00",
        checkOutTime: "12:00",
        amenities: ["Petronas Tower Views", "Infinity Pool", "Spa", "5 Restaurants", "Free WiFi", "Fitness Center", "Kids Club", "KLCC Park Access"],
        amenitiesBn: ["পেট্রোনাস টাওয়ার ভিউ", "ইনফিনিটি পুল", "স্পা", "৫টি রেস্তোরাঁ", "বিনামূল্যে ওয়াইফাই", "ফিটনেস সেন্টার", "কিডস ক্লাব", "কেএলসিসি পার্ক অ্যাক্সেস"],
        description: "Overlooking the iconic Petronas Twin Towers, Mandarin Oriental KL blends Asian heritage with contemporary luxury in the heart of the city.",
        descriptionBn: "আইকনিক পেট্রোনাস টুইন টাওয়ারের দৃশ্য সহ, ম্যান্ডারিন ওরিয়েন্টাল কেএল শহরের কেন্দ্রে এশিয়ান ঐতিহ্য ও আধুনিক বিলাসিতা মিশ্রিত করেছে।",
        longDescription: "Mandarin Oriental Kuala Lumpur enjoys a prime location within the Kuala Lumpur City Centre complex, adjacent to the iconic Petronas Twin Towers. Featuring 643 rooms and suites with stunning views of the towers or KLCC park, the hotel is home to 5 outstanding restaurants. The Mandarin Spa offers traditional Asian wellness treatments. Guests enjoy direct access to Suria KLCC shopping mall and the beautiful KLCC park.",
        longDescriptionBn: "ম্যান্ডারিন ওরিয়েন্টাল কুয়ালালামপুর পেট্রোনাস টুইন টাওয়ারের পাশে কেএলসিসি কমপ্লেক্সে একটি মূল অবস্থানে রয়েছে।",
        faqs: [
            { question: "Is the hotel close to Petronas Towers?", questionBn: "হোটেলটি কি পেট্রোনাস টাওয়ারের কাছে?", answer: "The hotel is adjacent to Petronas Twin Towers, connected by an indoor walkway.", answerBn: "হোটেলটি পেট্রোনাস টুইন টাওয়ারের পাশেই, একটি ইনডোর ওয়াকওয়ে দিয়ে সংযুক্ত।" },
        ],
        tags: ["Petronas View", "KL", "Luxury", "Shopping", "Business"],
        rating: 4.7,
        reviewsCount: 1870,
        status: "active",
        isActive: true,
        isFeatured: false,
        order: 8,
    },
    {
        name: "InterContinental Bangkok",
        nameBn: "ইন্টারকন্টিনেন্টাল ব্যাংকক",
        slug: "intercontinental-bangkok",
        image: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1179156/pexels-photo-1179156.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "973 Phloen Chit Road, Lumphini, Bangkok 10330, Thailand",
        locationBn: "৯৭৩ প্লোয়েন চিত রোড, লুমফিনি, ব্যাংকক ১০৩৩০, থাইল্যান্ড",
        city: "Bangkok",
        cityBn: "ব্যাংকক",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Club Room",
        roomTypeBn: "ক্লাব রুম",
        pricePerNight: 22000,
        oldPrice: 28000,
        currency: "BDT",
        totalRooms: 381,
        availableRooms: 72,
        checkInTime: "14:00",
        checkOutTime: "12:00",
        amenities: ["Free WiFi", "Rooftop Pool", "Fitness Center", "Spa", "Multiple Restaurants", "Club Lounge", "BTS Skytrain Access", "Business Center"],
        amenitiesBn: ["বিনামূল্যে ওয়াইফাই", "রুফটপ পুল", "ফিটনেস সেন্টার", "স্পা", "একাধিক রেস্তোরাঁ", "ক্লাব লাউঞ্জ", "বিটিএস স্কাইট্রেন অ্যাক্সেস", "বিজনেস সেন্টার"],
        description: "Centrally located on Phloen Chit Road with direct BTS Skytrain access, InterContinental Bangkok offers world-class luxury in the heart of Bangkok's shopping and business district.",
        descriptionBn: "সরাসরি বিটিএস স্কাইট্রেন অ্যাক্সেস সহ প্লোয়েন চিত রোডে কেন্দ্রীয়ভাবে অবস্থিত, ইন্টারকন্টিনেন্টাল ব্যাংকক শপিং ও বিজনেস ডিস্ট্রিক্টে বিশ্বমানের বিলাসিতা প্রদান করে।",
        longDescription: "InterContinental Bangkok is perfectly situated in the heart of the city's premier shopping and business district on Phloen Chit Road. The hotel's 381 rooms and suites offer contemporary Thai-inspired design with stunning city views. Enjoy rooftop dining, spa treatments inspired by Thai wellness traditions, and direct access to BTS Skytrain for exploring Bangkok's endless attractions including Chatuchak Weekend Market, Grand Palace, and Siam Paragon.",
        longDescriptionBn: "ইন্টারকন্টিনেন্টাল ব্যাংকক প্লোয়েন চিত রোডে শহরের প্রিমিয়ার শপিং ও বিজনেস ডিস্ট্রিক্টের কেন্দ্রে চমৎকারভাবে অবস্থিত।",
        faqs: [
            { question: "Is the hotel connected to BTS Skytrain?", questionBn: "হোটেলটি কি বিটিএস স্কাইট্রেনের সাথে সংযুক্ত?", answer: "Yes, Chit Lom BTS station is directly connected to the hotel.", answerBn: "হ্যাঁ, চিত লম বিটিএস স্টেশন সরাসরি হোটেলের সাথে সংযুক্ত।" },
        ],
        tags: ["BTS Connected", "Bangkok", "Shopping", "Business", "Luxury"],
        rating: 4.6,
        reviewsCount: 2140,
        status: "active",
        isActive: true,
        isFeatured: false,
        order: 9,
    },
    {
        name: "Hotel Himalaya Kathmandu",
        nameBn: "হোটেল হিমালয় কাঠমান্ডু",
        slug: "hotel-himalaya-kathmandu",
        image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&cs=tinysrgb&w=1200",
        gallery: [
            "https://images.pexels.com/photos/1559825/pexels-photo-1559825.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/803975/pexels-photo-803975.jpeg?auto=compress&cs=tinysrgb&w=800",
            "https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg?auto=compress&cs=tinysrgb&w=800",
        ],
        location: "Lalitpur-3, Kupandole, Kathmandu 44600, Nepal",
        locationBn: "ললিতপুর-৩, কুপান্ডোল, কাঠমান্ডু ৪৪৬০০, নেপাল",
        city: "Kathmandu",
        cityBn: "কাঠমান্ডু",
        starRating: 5,
        hotelCategory: "luxury",
        roomType: "Himalayan View Room",
        roomTypeBn: "হিমালয়ান ভিউ রুম",
        pricePerNight: 12500,
        oldPrice: 16000,
        currency: "BDT",
        totalRooms: 150,
        availableRooms: 38,
        checkInTime: "14:00",
        checkOutTime: "12:00",
        amenities: ["Himalayan View", "Outdoor Pool", "Spa", "Yoga Center", "Trekking Desk", "Free WiFi", "Multiple Restaurants", "Airport Transfer", "Currency Exchange"],
        amenitiesBn: ["হিমালয়ের দৃশ্য", "আউটডোর পুল", "স্পা", "যোগ কেন্দ্র", "ট্রেকিং ডেস্ক", "বিনামূল্যে ওয়াইফাই", "একাধিক রেস্তোরাঁ", "এয়ারপোর্ট ট্রান্সফার", "কারেন্সি এক্সচেঞ্জ"],
        description: "Experience the majestic beauty of the Himalayas from the comfort of Kathmandu's most iconic hotel, gateway to Everest trekking adventures.",
        descriptionBn: "কাঠমান্ডুর সবচেয়ে আইকনিক হোটেলের আরাম থেকে হিমালয়ের রাজকীয় সৌন্দর্য অনুভব করুন, এভারেস্ট ট্রেকিং অ্যাডভেঞ্চারের গেটওয়ে।",
        longDescription: "Hotel Himalaya Kathmandu is Nepal's finest hotel, offering breathtaking views of the Himalayan range including Langtang and Ganesh Himal peaks. Situated in the peaceful residential area of Lalitpur, the hotel provides a serene escape while being 15 minutes from Thamel and major attractions. The hotel's trekking desk can arrange Everest Base Camp, Annapurna, and Langtang treks. Experience authentic Nepali cuisine at Kakuri Restaurant and relax in the Himalayan Spa.",
        longDescriptionBn: "হোটেল হিমালয় কাঠমান্ডু নেপালের সেরা হোটেল, লাংটাং ও গণেশ হিমাল শিখর সহ হিমালয় পর্বতমালার শ্বাসরুদ্ধকর দৃশ্য সহ।",
        faqs: [
            { question: "Can the hotel arrange Everest Base Camp trek?", questionBn: "হোটেল কি এভারেস্ট বেস ক্যাম্প ট্রেক আয়োজন করতে পারে?", answer: "Yes, our trekking desk arranges EBC, Annapurna, and all major Nepal treks.", answerBn: "হ্যাঁ, আমাদের ট্রেকিং ডেস্ক ইবিসি, অন্নপূর্ণা এবং সব প্রধান নেপাল ট্রেক আয়োজন করে।" },
            { question: "What is the best time to visit Nepal?", questionBn: "নেপাল ভ্রমণের সেরা সময় কোনটি?", answer: "March-May and October-November are the ideal trekking seasons.", answerBn: "মার্চ-মে এবং অক্টোবর-নভেম্বর আদর্শ ট্রেকিং মৌসুম।" },
        ],
        tags: ["Himalayan View", "Trekking", "Nepal", "Adventure", "Yoga"],
        rating: 4.7,
        reviewsCount: 1120,
        status: "active",
        isActive: true,
        isFeatured: true,
        order: 10,
    },
];

async function seedHotels() {
    const client = new MongoClient(uri);
    try {
        await client.connect();
        console.log("✅ Connected to MongoDB Atlas");

        const db = client.db("visaprobd");
        const collection = db.collection("hotels");

        // Remove existing hotels
        const deleted = await collection.deleteMany({});
        console.log(`🗑️  Deleted ${deleted.deletedCount} existing hotels`);

        // Add timestamps
        const now = new Date();
        const hotelsWithTimestamps = hotels.map(hotel => ({
            ...hotel,
            createdAt: now,
            updatedAt: now,
        }));

        // Insert new hotels
        const result = await collection.insertMany(hotelsWithTimestamps);
        console.log(`✅ Inserted ${result.insertedCount} hotels successfully!`);

        // List inserted hotels
        console.log("\n📋 Inserted Hotels:");
        hotels.forEach((h, i) => {
            console.log(`  ${i + 1}. ${h.name} (${h.city}) - ⭐${h.starRating} - BDT ${h.pricePerNight.toLocaleString()}/night`);
        });

    } catch (error) {
        console.error("❌ Error:", error);
    } finally {
        await client.close();
        console.log("\n🔌 Connection closed");
    }
}

seedHotels();
