const { MongoClient } = require("mongodb");
const uri = "mongodb+srv://visaprobd:visaprobd@cluster0.b5kfivm.mongodb.net/visaprobd?appName=Cluster0";

const tours = [
    // ===== 5 Bangladesh Tours =====
    {
        title: "Sundarbans Mangrove Safari",
        titleBn: "সুন্দরবন ম্যানগ্রোভ সাফারি",
        slug: "sundarbans-mangrove-safari",
        image: "https://images.pexels.com/photos/2739013/pexels-photo-2739013.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Sundarbans, Bangladesh", destinationBn: "সুন্দরবন, বাংলাদেশ",
        category: "nature", tourType: "Group Tour", tourTypeBn: "গ্রুপ ট্যুর",
        duration: "03 Days 02 Nights", durationBn: "০৩ দিন ০২ রাত",
        price: 8500, oldPrice: 10000, currency: "BDT", groupSize: 20,
        description: "Explore the world's largest mangrove forest, home to the Royal Bengal Tiger.",
        descriptionBn: "বিশ্বের বৃহত্তম ম্যানগ্রোভ বন অন্বেষণ করুন, রয়েল বেঙ্গল টাইগারের আবাসস্থল।",
        longDescription: "Embark on a 3-day journey through the UNESCO World Heritage Sundarbans. Cruise through winding rivers, spot wildlife including deer, crocodiles, and if lucky, the Royal Bengal Tiger. Experience the unique ecosystem of tidal waterways and mudflats.",
        longDescriptionBn: "ইউনেস্কো ওয়ার্ল্ড হেরিটেজ সুন্দরবনের মধ্য দিয়ে ৩ দিনের যাত্রায় বেরিয়ে পড়ুন। আঁকাবাঁকা নদী দিয়ে ক্রুজ করুন, হরিণ, কুমির এবং ভাগ্য ভালো থাকলে রয়েল বেঙ্গল টাইগার দেখুন।",
        itinerary: [
            { day: 1, title: "Departure from Khulna", titleBn: "খুলনা থেকে যাত্রা", description: "Board the launch from Khulna, cruise to Sundarbans.", descriptionBn: "খুলনা থেকে লঞ্চে সুন্দরবনের উদ্দেশ্যে যাত্রা।" },
            { day: 2, title: "Jungle Trail & Watch Towers", titleBn: "জঙ্গল ট্রেইল ও ওয়াচ টাওয়ার", description: "Trek through Katka, Kachikhali trails, visit watch towers.", descriptionBn: "কটকা, কচিখালি ট্রেইলে ট্রেকিং, ওয়াচ টাওয়ার পরিদর্শন।" },
            { day: 3, title: "Return to Khulna", titleBn: "খুলনায় প্রত্যাবর্তন", description: "Morning bird watching, return cruise to Khulna.", descriptionBn: "সকালে পাখি দেখা, খুলনায় ফিরতি ক্রুজ।" },
        ],
        includes: ["Launch accommodation", "All meals (breakfast, lunch, dinner)", "Forest guide", "Entry permits", "Binoculars"],
        includesBn: ["লঞ্চে থাকা", "সব খাবার (সকাল, দুপুর, রাত)", "ফরেস্ট গাইড", "প্রবেশ অনুমতি", "বাইনোকুলার"],
        excludes: ["Personal expenses", "Tips", "Travel insurance"],
        excludesBn: ["ব্যক্তিগত খরচ", "টিপস", "ভ্রমণ বীমা"],
        tags: ["Wildlife", "Nature", "Adventure"], rating: 4.8, reviewsCount: 156,
        faqs: [
            { question: "Is it safe?", questionBn: "এটা কি নিরাপদ?", answer: "Yes, experienced guides ensure safety throughout.", answerBn: "হ্যাঁ, অভিজ্ঞ গাইড পুরো সময় নিরাপত্তা নিশ্চিত করে।" },
            { question: "Best time to visit?", questionBn: "ভ্রমণের সেরা সময়?", answer: "November to February is ideal.", answerBn: "নভেম্বর থেকে ফেব্রুয়ারি আদর্শ।" },
        ],
        status: "active", isActive: true, isFeatured: true, order: 1,
    },
    {
        title: "Cox's Bazar Beach Getaway",
        titleBn: "কক্সবাজার সমুদ্র সৈকত ভ্রমণ",
        slug: "coxs-bazar-beach-getaway",
        image: "https://images.pexels.com/photos/1078983/pexels-photo-1078983.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Cox's Bazar, Bangladesh", destinationBn: "কক্সবাজার, বাংলাদেশ",
        category: "beach", tourType: "Family Tour", tourTypeBn: "ফ্যামিলি ট্যুর",
        duration: "04 Days 03 Nights", durationBn: "০৪ দিন ০৩ রাত",
        price: 12000, oldPrice: 15000, currency: "BDT", groupSize: 25,
        description: "Enjoy the world's longest natural sea beach with stunning sunsets.",
        descriptionBn: "বিশ্বের দীর্ঘতম প্রাকৃতিক সমুদ্র সৈকতে অপরূপ সূর্যাস্ত উপভোগ করুন।",
        longDescription: "Experience 4 days at the world's longest unbroken sea beach. Visit Himchari waterfall, Inani Beach's coral stones, and Saint Martin Island. Enjoy fresh seafood and breathtaking sunsets over the Bay of Bengal.",
        longDescriptionBn: "বিশ্বের দীর্ঘতম অবিচ্ছিন্ন সমুদ্র সৈকতে ৪ দিনের অভিজ্ঞতা নিন। হিমছড়ি জলপ্রপাত, ইনানী বিচের প্রবাল পাথর এবং সেন্ট মার্টিন দ্বীপ পরিদর্শন করুন।",
        itinerary: [
            { day: 1, title: "Arrival & Sugandha Beach", titleBn: "আগমন ও সুগন্ধা বিচ", description: "Check-in, evening beach walk at Sugandha Point.", descriptionBn: "চেক-ইন, সুগন্ধা পয়েন্টে সন্ধ্যার বিচ ওয়াক।" },
            { day: 2, title: "Himchari & Inani", titleBn: "হিমছড়ি ও ইনানী", description: "Visit Himchari waterfall and Inani coral beach.", descriptionBn: "হিমছড়ি জলপ্রপাত ও ইনানী প্রবাল বিচ পরিদর্শন।" },
            { day: 3, title: "Marine Drive", titleBn: "মেরিন ড্রাইভ", description: "Drive along 80km Marine Drive road, Teknaf visit.", descriptionBn: "৮০ কিমি মেরিন ড্রাইভ রোডে ড্রাইভ, টেকনাফ পরিদর্শন।" },
            { day: 4, title: "Departure", titleBn: "প্রস্থান", description: "Morning shopping, checkout and departure.", descriptionBn: "সকালে শপিং, চেক-আউট ও প্রস্থান।" },
        ],
        includes: ["3-star hotel", "Daily breakfast", "AC transport", "Sightseeing guide"],
        includesBn: ["৩-তারা হোটেল", "দৈনিক সকালের খাবার", "এসি পরিবহন", "দর্শনীয় স্থান গাইড"],
        tags: ["Beach", "Family", "Sunset"], rating: 4.7, reviewsCount: 230,
        faqs: [{ question: "Is swimming safe?", questionBn: "সাঁতার কি নিরাপদ?", answer: "Yes, designated safe zones are available.", answerBn: "হ্যাঁ, নির্ধারিত নিরাপদ জোন আছে।" }],
        status: "active", isActive: true, isFeatured: true, order: 2,
    },
    {
        title: "Bandarban Hill Trekking Adventure",
        titleBn: "বান্দরবান পাহাড় ট্রেকিং অ্যাডভেঞ্চার",
        slug: "bandarban-hill-trekking",
        image: "https://images.pexels.com/photos/2387418/pexels-photo-2387418.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Bandarban, Bangladesh", destinationBn: "বান্দরবান, বাংলাদেশ",
        category: "hill", tourType: "Group Tour", tourTypeBn: "গ্রুপ ট্যুর",
        duration: "03 Days 02 Nights", durationBn: "০৩ দিন ০২ রাত",
        price: 7500, oldPrice: 9000, currency: "BDT", groupSize: 15,
        description: "Trek through the highest peaks of Bangladesh with breathtaking cloud views.",
        descriptionBn: "বাংলাদেশের সর্বোচ্চ চূড়ায় ট্রেকিং করুন মেঘের অপূর্ব দৃশ্যের সাথে।",
        longDescription: "Adventure through Bandarban's stunning hill tracts. Visit Nilgiri, the highest accessible peak. Trek to Nafakhum waterfall, cross hanging bamboo bridges, and experience indigenous tribal culture. Perfect for adventure seekers.",
        longDescriptionBn: "বান্দরবানের অসাধারণ পাহাড়ি অঞ্চলে অ্যাডভেঞ্চার করুন। নীলগিরি পরিদর্শন করুন। নাফাখুম জলপ্রপাতে ট্রেক করুন এবং আদিবাসী সংস্কৃতি অনুভব করুন।",
        itinerary: [
            { day: 1, title: "Nilgiri & Golden Temple", titleBn: "নীলগিরি ও সোনালী মন্দির", description: "Drive to Nilgiri, visit Golden Temple.", descriptionBn: "নীলগিরিতে ড্রাইভ, সোনালী মন্দির পরিদর্শন।" },
            { day: 2, title: "Nafakhum Trek", titleBn: "নাফাখুম ট্রেক", description: "Full day trek to Nafakhum waterfall.", descriptionBn: "নাফাখুম জলপ্রপাতে পুরো দিনের ট্রেক।" },
            { day: 3, title: "Shoilo Propat & Return", titleBn: "শৈল প্রপাত ও প্রত্যাবর্তন", description: "Visit Shoilo Propat waterfall, return.", descriptionBn: "শৈল প্রপাত জলপ্রপাত পরিদর্শন, ফিরতি যাত্রা।" },
        ],
        includes: ["Resort stay", "All meals", "Trekking guide", "Transport"],
        includesBn: ["রিসোর্টে থাকা", "সব খাবার", "ট্রেকিং গাইড", "পরিবহন"],
        tags: ["Trekking", "Hill", "Adventure"], rating: 4.6, reviewsCount: 89,
        status: "active", isActive: true, isFeatured: false, order: 3,
    },
    {
        title: "Sylhet Tea Garden & Waterfall Tour",
        titleBn: "সিলেট চা বাগান ও জলপ্রপাত ট্যুর",
        slug: "sylhet-tea-garden-waterfall",
        image: "https://images.pexels.com/photos/2105882/pexels-photo-2105882.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Sylhet, Bangladesh", destinationBn: "সিলেট, বাংলাদেশ",
        category: "nature", tourType: "Couple Tour", tourTypeBn: "কাপল ট্যুর",
        duration: "03 Days 02 Nights", durationBn: "০৩ দিন ০২ রাত",
        price: 9000, oldPrice: 11000, currency: "BDT", groupSize: 12,
        description: "Walk through lush green tea gardens and discover hidden waterfalls.",
        descriptionBn: "সবুজ চা বাগানে হাঁটুন এবং লুকানো জলপ্রপাত আবিষ্কার করুন।",
        longDescription: "Discover the natural beauty of Sylhet — endless tea gardens of Sreemangal, the mystical Ratargul swamp forest, Bichanakandi's crystal clear water, and Madhabkunda waterfall. A perfect romantic getaway.",
        longDescriptionBn: "সিলেটের প্রাকৃতিক সৌন্দর্য আবিষ্কার করুন — শ্রীমঙ্গলের অন্তহীন চা বাগান, রাতারগুল জলাবন, বিছানাকান্দির স্বচ্ছ জল এবং মাধবকুণ্ড জলপ্রপাত।",
        itinerary: [
            { day: 1, title: "Sreemangal Tea Gardens", titleBn: "শ্রীমঙ্গল চা বাগান", description: "Visit tea gardens, Lawachara forest.", descriptionBn: "চা বাগান ও লাউয়াছড়া বন পরিদর্শন।" },
            { day: 2, title: "Ratargul & Bichanakandi", titleBn: "রাতারগুল ও বিছানাকান্দি", description: "Boat ride in Ratargul, Bichanakandi trip.", descriptionBn: "রাতারগুলে নৌকা ভ্রমণ, বিছানাকান্দি ট্রিপ।" },
            { day: 3, title: "Madhabkunda & Return", titleBn: "মাধবকুণ্ড ও ফিরতি", description: "Madhabkunda waterfall visit, departure.", descriptionBn: "মাধবকুণ্ড জলপ্রপাত পরিদর্শন, প্রস্থান।" },
        ],
        includes: ["Hotel stay", "Breakfast & dinner", "AC transport", "Boat rides"],
        includesBn: ["হোটেলে থাকা", "সকাল ও রাতের খাবার", "এসি পরিবহন", "নৌকা ভ্রমণ"],
        tags: ["Tea Garden", "Waterfall", "Romantic"], rating: 4.9, reviewsCount: 178,
        status: "active", isActive: true, isFeatured: true, order: 4,
    },
    {
        title: "Rangamati Lake & Tribal Culture",
        titleBn: "রাঙামাটি লেক ও আদিবাসী সংস্কৃতি",
        slug: "rangamati-lake-tribal-culture",
        image: "https://images.pexels.com/photos/1586298/pexels-photo-1586298.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Rangamati, Bangladesh", destinationBn: "রাঙামাটি, বাংলাদেশ",
        category: "culture", tourType: "Family Tour", tourTypeBn: "ফ্যামিলি ট্যুর",
        duration: "02 Days 01 Night", durationBn: "০২ দিন ০১ রাত",
        price: 6000, oldPrice: 7500, currency: "BDT", groupSize: 18,
        description: "Cruise on Kaptai Lake and explore vibrant tribal heritage.",
        descriptionBn: "কাপ্তাই লেকে ক্রুজ করুন এবং প্রাণবন্ত আদিবাসী ঐতিহ্য অন্বেষণ করুন।",
        longDescription: "Experience the serene beauty of Kaptai Lake, visit the Hanging Bridge, Shuvolong waterfall, and Rajban Bihar. Immerse yourself in Chakma and Marma tribal culture, taste their traditional cuisine, and enjoy a peaceful lake cruise.",
        longDescriptionBn: "কাপ্তাই লেকের শান্ত সৌন্দর্য অনুভব করুন, ঝুলন্ত সেতু, শুভলং জলপ্রপাত এবং রাজবন বিহার পরিদর্শন করুন। চাকমা ও মারমা আদিবাসী সংস্কৃতিতে নিজেকে নিমজ্জিত করুন।",
        itinerary: [
            { day: 1, title: "Kaptai Lake Cruise", titleBn: "কাপ্তাই লেক ক্রুজ", description: "Boat cruise, Shuvolong waterfall, Hanging Bridge.", descriptionBn: "নৌকা ক্রুজ, শুভলং জলপ্রপাত, ঝুলন্ত সেতু।" },
            { day: 2, title: "Tribal Village & Return", titleBn: "আদিবাসী গ্রাম ও ফিরতি", description: "Visit tribal village, Rajban Bihar, return.", descriptionBn: "আদিবাসী গ্রাম, রাজবন বিহার পরিদর্শন, ফিরতি।" },
        ],
        includes: ["Hotel stay", "All meals", "Boat cruise", "Guide"],
        includesBn: ["হোটেলে থাকা", "সব খাবার", "নৌকা ক্রুজ", "গাইড"],
        tags: ["Lake", "Culture", "Tribal"], rating: 4.5, reviewsCount: 67,
        status: "active", isActive: true, isFeatured: false, order: 5,
    },
    // ===== 5 International Tours =====
    {
        title: "Makkah & Madinah Umrah Package",
        titleBn: "মক্কা ও মদিনা উমরাহ প্যাকেজ",
        slug: "makkah-madinah-umrah-package",
        image: "https://images.pexels.com/photos/2818108/pexels-photo-2818108.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Saudi Arabia", destinationBn: "সৌদি আরব",
        category: "religious", tourType: "Group Tour", tourTypeBn: "গ্রুপ ট্যুর",
        duration: "10 Days 09 Nights", durationBn: "১০ দিন ০৯ রাত",
        price: 185000, oldPrice: 210000, currency: "BDT", groupSize: 40,
        description: "Complete Umrah package with 5-star hotels near Haram Sharif.",
        descriptionBn: "হারাম শরীফের কাছে ৫-তারা হোটেলসহ সম্পূর্ণ উমরাহ প্যাকেজ।",
        longDescription: "Perform your sacred Umrah with our premium package. Stay in 5-star hotels within walking distance of Masjid al-Haram and Masjid an-Nabawi. Includes Ziyarah tours to historical Islamic sites in both holy cities.",
        longDescriptionBn: "আমাদের প্রিমিয়াম প্যাকেজে আপনার পবিত্র উমরাহ পালন করুন। মসজিদ আল-হারাম ও মসজিদ আন-নববীর হাঁটা দূরত্বে ৫-তারা হোটেলে থাকুন।",
        itinerary: [
            { day: 1, title: "Departure from Dhaka", titleBn: "ঢাকা থেকে যাত্রা", description: "Flight to Jeddah, transfer to Makkah.", descriptionBn: "জেদ্দায় ফ্লাইট, মক্কায় ট্রান্সফার।" },
            { day: 2, title: "Umrah Performance", titleBn: "উমরাহ পালন", description: "Perform Umrah rituals with guide.", descriptionBn: "গাইডের সাথে উমরাহ পালন।" },
            { day: 3, title: "Makkah Ziyarah", titleBn: "মক্কা জিয়ারত", description: "Visit Jabal Nur, Jabal Thawr, Mina.", descriptionBn: "জাবালে নূর, জাবালে সাওর, মিনা পরিদর্শন।" },
            { day: 4, title: "Free Day Makkah", titleBn: "মক্কায় ফ্রি দিন", description: "Prayers and personal time at Haram.", descriptionBn: "হারামে নামাজ ও ব্যক্তিগত সময়।" },
            { day: 5, title: "Travel to Madinah", titleBn: "মদিনায় যাত্রা", description: "AC bus to Madinah, hotel check-in.", descriptionBn: "এসি বাসে মদিনা, হোটেল চেক-ইন।" },
            { day: 6, title: "Madinah Ziyarah", titleBn: "মদিনা জিয়ারত", description: "Visit Uhud, Quba Mosque, Date Market.", descriptionBn: "উহুদ, কুবা মসজিদ, খেজুর বাজার পরিদর্শন।" },
            { day: 7, title: "Return to Dhaka", titleBn: "ঢাকায় ফিরতি", description: "Flight back to Dhaka.", descriptionBn: "ঢাকায় ফিরতি ফ্লাইট।" },
        ],
        includes: ["Return air ticket", "5-star hotel (Makkah & Madinah)", "Visa processing", "Ziyarah transport", "All meals", "Umrah guide"],
        includesBn: ["রিটার্ন বিমান টিকিট", "৫-তারা হোটেল (মক্কা ও মদিনা)", "ভিসা প্রসেসিং", "জিয়ারত পরিবহন", "সব খাবার", "উমরাহ গাইড"],
        tags: ["Umrah", "Religious", "Holy"], rating: 4.9, reviewsCount: 340,
        status: "active", isActive: true, isFeatured: true, order: 6,
    },
    {
        title: "Dubai City & Desert Safari",
        titleBn: "দুবাই সিটি ও ডেজার্ট সাফারি",
        slug: "dubai-city-desert-safari",
        image: "https://images.pexels.com/photos/2044434/pexels-photo-2044434.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Dubai, UAE", destinationBn: "দুবাই, সংযুক্ত আরব আমিরাত",
        category: "city", tourType: "Family Tour", tourTypeBn: "ফ্যামিলি ট্যুর",
        duration: "05 Days 04 Nights", durationBn: "০৫ দিন ০৪ রাত",
        price: 95000, oldPrice: 120000, currency: "BDT", groupSize: 20,
        description: "From Burj Khalifa to golden desert sands, experience the magic of Dubai.",
        descriptionBn: "বুর্জ খলিফা থেকে সোনালী মরুভূমির বালু পর্যন্ত, দুবাইয়ের জাদু অনুভব করুন।",
        longDescription: "Experience the glittering city of Dubai. Visit Burj Khalifa, Dubai Mall, Palm Jumeirah, and enjoy a thrilling desert safari with BBQ dinner under the stars. A perfect blend of luxury, adventure, and culture.",
        longDescriptionBn: "দুবাইয়ের ঝলমলে শহরের অভিজ্ঞতা নিন। বুর্জ খলিফা, দুবাই মল, পাম জুমেইরাহ পরিদর্শন করুন এবং তারার নিচে বিবিকিউ ডিনার সহ ডেজার্ট সাফারি উপভোগ করুন।",
        itinerary: [
            { day: 1, title: "Arrival & City Tour", titleBn: "আগমন ও সিটি ট্যুর", description: "Burj Khalifa, Dubai Mall, Fountain Show.", descriptionBn: "বুর্জ খলিফা, দুবাই মল, ফাউন্টেন শো।" },
            { day: 2, title: "Old Dubai & Souks", titleBn: "পুরাতন দুবাই ও সুক", description: "Gold Souk, Spice Souk, Abra ride.", descriptionBn: "গোল্ড সুক, স্পাইস সুক, আবরা রাইড।" },
            { day: 3, title: "Desert Safari", titleBn: "ডেজার্ট সাফারি", description: "Dune bashing, camel ride, BBQ dinner.", descriptionBn: "ডিউন ব্যাশিং, উটে চড়া, বিবিকিউ ডিনার।" },
            { day: 4, title: "Palm & Marina", titleBn: "পাম ও মেরিনা", description: "Palm Jumeirah, Atlantis, Marina cruise.", descriptionBn: "পাম জুমেইরাহ, আটলান্টিস, মেরিনা ক্রুজ।" },
            { day: 5, title: "Departure", titleBn: "প্রস্থান", description: "Shopping time, airport transfer.", descriptionBn: "শপিং টাইম, এয়ারপোর্ট ট্রান্সফার।" },
        ],
        includes: ["Air ticket", "4-star hotel", "Desert safari", "City tour", "Visa", "Breakfast"],
        includesBn: ["বিমান টিকিট", "৪-তারা হোটেল", "ডেজার্ট সাফারি", "সিটি ট্যুর", "ভিসা", "সকালের খাবার"],
        tags: ["City", "Safari", "Luxury"], rating: 4.8, reviewsCount: 210,
        status: "active", isActive: true, isFeatured: true, order: 7,
    },
    {
        title: "Thailand: Bangkok & Pattaya",
        titleBn: "থাইল্যান্ড: ব্যাংকক ও পাতায়া",
        slug: "thailand-bangkok-pattaya",
        image: "https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Thailand", destinationBn: "থাইল্যান্ড",
        category: "international", tourType: "Group Tour", tourTypeBn: "গ্রুপ ট্যুর",
        duration: "05 Days 04 Nights", durationBn: "০৫ দিন ০৪ রাত",
        price: 55000, oldPrice: 65000, currency: "BDT", groupSize: 25,
        description: "Explore vibrant Bangkok temples and Pattaya's beautiful beaches.",
        descriptionBn: "ব্যাংককের প্রাণবন্ত মন্দির এবং পাতায়ার সুন্দর সমুদ্র সৈকত অন্বেষণ করুন।",
        longDescription: "5 days of Thai adventure — visit Grand Palace, Wat Pho, floating markets in Bangkok, then relax on Pattaya's beaches, visit Coral Island, and enjoy Alcazar Cabaret Show.",
        longDescriptionBn: "৫ দিনের থাই অ্যাডভেঞ্চার — ব্যাংককে গ্র্যান্ড প্যালেস, ওয়াট ফো, ভাসমান বাজার পরিদর্শন করুন, তারপর পাতায়ার সৈকতে বিশ্রাম নিন।",
        itinerary: [
            { day: 1, title: "Bangkok Arrival", titleBn: "ব্যাংকক আগমন", description: "Airport pickup, Khao San Road.", descriptionBn: "এয়ারপোর্ট পিকআপ, খাও সান রোড।" },
            { day: 2, title: "Bangkok Temples", titleBn: "ব্যাংকক মন্দির", description: "Grand Palace, Wat Pho, Wat Arun.", descriptionBn: "গ্র্যান্ড প্যালেস, ওয়াট ফো, ওয়াট অরুণ।" },
            { day: 3, title: "Pattaya Transfer", titleBn: "পাতায়া ট্রান্সফার", description: "Travel to Pattaya, Coral Island.", descriptionBn: "পাতায়ায় যাত্রা, কোরাল আইল্যান্ড।" },
            { day: 4, title: "Pattaya City", titleBn: "পাতায়া সিটি", description: "Alcazar Show, Walking Street.", descriptionBn: "আলকাজার শো, ওয়াকিং স্ট্রিট।" },
            { day: 5, title: "Departure", titleBn: "প্রস্থান", description: "Return flight to Dhaka.", descriptionBn: "ঢাকায় রিটার্ন ফ্লাইট।" },
        ],
        includes: ["Air ticket", "3-star hotel", "City tours", "Coral Island trip", "Breakfast"],
        includesBn: ["বিমান টিকিট", "৩-তারা হোটেল", "সিটি ট্যুর", "কোরাল আইল্যান্ড ট্রিপ", "সকালের খাবার"],
        tags: ["International", "Beach", "Budget"], rating: 4.6, reviewsCount: 145,
        status: "active", isActive: true, isFeatured: false, order: 8,
    },
    {
        title: "Kashmir: Paradise on Earth",
        titleBn: "কাশ্মীর: পৃথিবীর স্বর্গ",
        slug: "kashmir-paradise-on-earth",
        image: "https://images.pexels.com/photos/2prior587/pexels-photo-2587.jpeg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Kashmir, India", destinationBn: "কাশ্মীর, ভারত",
        category: "nature", tourType: "Couple Tour", tourTypeBn: "কাপল ট্যুর",
        duration: "06 Days 05 Nights", durationBn: "০৬ দিন ০৫ রাত",
        price: 45000, oldPrice: 55000, currency: "BDT", groupSize: 15,
        description: "Experience snow-capped mountains, Dal Lake houseboats, and Mughal gardens.",
        descriptionBn: "তুষারাবৃত পাহাড়, ডাল লেকের হাউসবোট এবং মুঘল বাগান অনুভব করুন।",
        longDescription: "Discover why Kashmir is called Paradise on Earth. Stay in a traditional houseboat on Dal Lake, visit the stunning Mughal Gardens, take a Gondola ride in Gulmarg, and explore the meadows of Pahalgam.",
        longDescriptionBn: "কাশ্মীরকে কেন পৃথিবীর স্বর্গ বলা হয় তা আবিষ্কার করুন। ডাল লেকে ঐতিহ্যবাহী হাউসবোটে থাকুন, মুঘল গার্ডেন পরিদর্শন করুন, গুলমার্গে গন্ডোলা রাইড করুন।",
        itinerary: [
            { day: 1, title: "Srinagar Arrival", titleBn: "শ্রীনগর আগমন", description: "Airport pickup, Dal Lake Shikara ride.", descriptionBn: "এয়ারপোর্ট পিকআপ, ডাল লেক শিকারা রাইড।" },
            { day: 2, title: "Mughal Gardens", titleBn: "মুঘল গার্ডেন", description: "Nishat Bagh, Shalimar Bagh, Tulip Garden.", descriptionBn: "নিশাত বাগ, শালিমার বাগ, টিউলিপ গার্ডেন।" },
            { day: 3, title: "Gulmarg Day Trip", titleBn: "গুলমার্গ দিবস ভ্রমণ", description: "Gondola ride, snow activities.", descriptionBn: "গন্ডোলা রাইড, স্নো অ্যাক্টিভিটিজ।" },
            { day: 4, title: "Pahalgam Excursion", titleBn: "পহেলগাম ভ্রমণ", description: "Betaab Valley, Aru Valley, Chandanwari.", descriptionBn: "বেতাব ভ্যালি, আরু ভ্যালি, চন্দনওয়ারি।" },
            { day: 5, title: "Sonmarg Trip", titleBn: "সোনমার্গ ট্রিপ", description: "Thajiwas Glacier, Zero Point.", descriptionBn: "থাজিওয়াস গ্লেসিয়ার, জিরো পয়েন্ট।" },
            { day: 6, title: "Departure", titleBn: "প্রস্থান", description: "Houseboat breakfast, airport transfer.", descriptionBn: "হাউসবোটে সকালের খাবার, এয়ারপোর্ট ট্রান্সফার।" },
        ],
        includes: ["Air ticket", "Houseboat + hotel", "All sightseeing", "Shikara ride", "Breakfast & dinner"],
        includesBn: ["বিমান টিকিট", "হাউসবোট + হোটেল", "সকল দর্শনীয় স্থান", "শিকারা রাইড", "সকাল ও রাতের খাবার"],
        tags: ["Snow", "Romantic", "Nature"], rating: 4.8, reviewsCount: 198,
        status: "active", isActive: true, isFeatured: true, order: 9,
    },
    {
        title: "Malaysia: Kuala Lumpur & Langkawi",
        titleBn: "মালয়েশিয়া: কুয়ালালামপুর ও লাঙ্কাউই",
        slug: "malaysia-kuala-lumpur-langkawi",
        image: "https://images.pexels.com/photos/22804/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
        destination: "Malaysia", destinationBn: "মালয়েশিয়া",
        category: "international", tourType: "Family Tour", tourTypeBn: "ফ্যামিলি ট্যুর",
        duration: "06 Days 05 Nights", durationBn: "০৬ দিন ০৫ রাত",
        price: 65000, oldPrice: 78000, currency: "BDT", groupSize: 20,
        description: "Visit the iconic Petronas Towers and relax on Langkawi's pristine beaches.",
        descriptionBn: "আইকনিক পেট্রোনাস টাওয়ার পরিদর্শন করুন এবং লাঙ্কাউইয়ের সৈকতে বিশ্রাম নিন।",
        longDescription: "Explore the best of Malaysia — the modern skyline of Kuala Lumpur with Petronas Twin Towers, Batu Caves, and vibrant street food. Then fly to Langkawi for island hopping, cable car rides, and duty-free shopping.",
        longDescriptionBn: "মালয়েশিয়ার সেরা অন্বেষণ করুন — পেট্রোনাস টুইন টাওয়ার, বাটু কেভসের সাথে কুয়ালালামপুরের আধুনিক স্কাইলাইন। তারপর আইল্যান্ড হপিং ও কেবল কার রাইডের জন্য লাঙ্কাউইতে উড়ুন।",
        itinerary: [
            { day: 1, title: "KL Arrival", titleBn: "কেএল আগমন", description: "Airport transfer, Petronas Towers visit.", descriptionBn: "এয়ারপোর্ট ট্রান্সফার, পেট্রোনাস টাওয়ার পরিদর্শন।" },
            { day: 2, title: "KL City Tour", titleBn: "কেএল সিটি ট্যুর", description: "Batu Caves, Chinatown, KL Tower.", descriptionBn: "বাটু কেভস, চায়নাটাউন, কেএল টাওয়ার।" },
            { day: 3, title: "Fly to Langkawi", titleBn: "লাঙ্কাউইতে ফ্লাই", description: "Domestic flight, beach resort check-in.", descriptionBn: "ডমেস্টিক ফ্লাইট, বিচ রিসোর্ট চেক-ইন।" },
            { day: 4, title: "Island Hopping", titleBn: "আইল্যান্ড হপিং", description: "Visit Pregnant Maiden Island, Eagle Square.", descriptionBn: "প্রেগন্যান্ট মেইডেন আইল্যান্ড, ঈগল স্কোয়ার পরিদর্শন।" },
            { day: 5, title: "Cable Car & Shopping", titleBn: "কেবল কার ও শপিং", description: "Sky Bridge, duty-free shopping.", descriptionBn: "স্কাই ব্রিজ, ডিউটি-ফ্রি শপিং।" },
            { day: 6, title: "Departure", titleBn: "প্রস্থান", description: "Return flight to Dhaka.", descriptionBn: "ঢাকায় রিটার্ন ফ্লাইট।" },
        ],
        includes: ["Air tickets (int'l + domestic)", "Hotels & resort", "City tours", "Island hopping", "Breakfast"],
        includesBn: ["বিমান টিকিট (আন্তর্জাতিক + ডমেস্টিক)", "হোটেল ও রিসোর্ট", "সিটি ট্যুর", "আইল্যান্ড হপিং", "সকালের খাবার"],
        tags: ["International", "Island", "Shopping"], rating: 4.7, reviewsCount: 167,
        status: "active", isActive: true, isFeatured: false, order: 10,
    },
];

async function seed() {
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db("visaprobd");
        const col = db.collection("tours");
        const existing = await col.countDocuments();
        if (existing > 0) {
            console.log(`⚠️  Already ${existing} tours exist. Dropping and re-seeding...`);
            await col.deleteMany({});
        }
        const now = new Date();
        const docs = tours.map(t => ({ ...t, createdAt: now, updatedAt: now }));
        const result = await col.insertMany(docs);
        console.log(`✅ Successfully inserted ${result.insertedCount} tours!`);
        const all = await col.find({}, { projection: { title: 1, destination: 1, price: 1 } }).toArray();
        all.forEach((t, i) => console.log(`  ${i + 1}. ${t.title} — ${t.destination} — ৳${t.price}`));
    } catch (err) {
        console.error("❌ Error:", err.message);
    } finally {
        await client.close();
    }
}

seed();
