import { z } from 'zod';

const createHajjUmrahZodSchema = z.object({
    body: z.object({
        name: z.string({ required_error: 'Package name is required' }),
        nameBn: z.string().optional(),
        type: z.enum(['hajj', 'umrah']).default('umrah'),
        subtitle: z.string().optional(),
        subtitleBn: z.string().optional(),
        image: z.string().optional(),
        duration: z.string({ required_error: 'Duration is required' }),
        durationBn: z.string().optional(),
        price: z.number({ required_error: 'Price is required' }),
        oldPrice: z.number().optional(),
        currency: z.string().optional(),
        groupSize: z.number().optional(),
        bookings: z.number().optional(),
        departureDate: z.string().optional(),
        departureDates: z.array(z.string()).optional(),
        hotel: z.string().optional(),
        hotelBn: z.string().optional(),
        distance: z.string().optional(),
        distanceBn: z.string().optional(),
        meals: z.string().optional(),
        mealsBn: z.string().optional(),
        description: z.string().optional(),
        descriptionBn: z.string().optional(),
        longDescription: z.string().optional(),
        longDescriptionBn: z.string().optional(),
        features: z.array(z.string()).default([]),
        featuresBn: z.array(z.string()).optional(),
        excludes: z.array(z.string()).optional(),
        excludesBn: z.array(z.string()).optional(),
        tags: z.array(z.string()).optional(),
        isPopular: z.boolean().optional(),
        status: z.enum(['active', 'upcoming', 'completed', 'cancelled']).optional(),
        isActive: z.boolean().optional(),
        isFeatured: z.boolean().optional(),
        order: z.number().optional(),
        metaTitle: z.string().optional(),
        metaDescription: z.string().optional(),
    }),
});

const updateHajjUmrahZodSchema = z.object({
    body: z.object({
        name: z.string().optional(),
        nameBn: z.string().optional(),
        type: z.enum(['hajj', 'umrah']).optional(),
        subtitle: z.string().optional(),
        subtitleBn: z.string().optional(),
        image: z.string().optional(),
        duration: z.string().optional(),
        durationBn: z.string().optional(),
        price: z.number().optional(),
        oldPrice: z.number().optional(),
        currency: z.string().optional(),
        groupSize: z.number().optional(),
        bookings: z.number().optional(),
        departureDate: z.string().optional(),
        departureDates: z.array(z.string()).optional(),
        hotel: z.string().optional(),
        hotelBn: z.string().optional(),
        distance: z.string().optional(),
        distanceBn: z.string().optional(),
        meals: z.string().optional(),
        mealsBn: z.string().optional(),
        description: z.string().optional(),
        descriptionBn: z.string().optional(),
        longDescription: z.string().optional(),
        longDescriptionBn: z.string().optional(),
        features: z.array(z.string()).optional(),
        featuresBn: z.array(z.string()).optional(),
        excludes: z.array(z.string()).optional(),
        excludesBn: z.array(z.string()).optional(),
        tags: z.array(z.string()).optional(),
        isPopular: z.boolean().optional(),
        status: z.enum(['active', 'upcoming', 'completed', 'cancelled']).optional(),
        isActive: z.boolean().optional(),
        isFeatured: z.boolean().optional(),
        order: z.number().optional(),
        metaTitle: z.string().optional(),
        metaDescription: z.string().optional(),
    }),
});

export const HajjUmrahValidation = { createHajjUmrahZodSchema, updateHajjUmrahZodSchema };
