import { Schema, model } from 'mongoose';

const docEntrySchema = new Schema(
    {
        documentType: { type: String, default: '' },
        documentNumber: { type: String, default: '' },
        fullNameEn: { type: String, default: '' },
        fullNameBn: { type: String, default: '' },
        dateOfBirth: { type: String, default: '' },
        placeOfBirth: { type: String, default: '' },
        gender: { type: String, default: 'Male' },
        nationality: { type: String, default: 'Bangladeshi' },
        religion: { type: String, default: '' },
        maritalStatus: { type: String, default: '' },
        occupation: { type: String, default: '' },
        fatherName: { type: String, default: '' },
        motherName: { type: String, default: '' },
        passportNo: { type: String, default: '' },
        passportIssueDate: { type: String, default: '' },
        passportExpiryDate: { type: String, default: '' },
        passportIssuePlace: { type: String, default: '' },
        visaType: { type: String, default: '' },
        visaNumber: { type: String, default: '' },
        country: { type: String, default: '' },
        embassyName: { type: String, default: '' },
        visaIssueDate: { type: String, default: '' },
        visaValidFrom: { type: String, default: '' },
        visaExpiryDate: { type: String, default: '' },
        entryType: { type: String, default: '' },
        durationOfStay: { type: String, default: '' },
        numberOfEntries: { type: String, default: '' },
        purposeOfVisit: { type: String, default: '' },
        airlineName: { type: String, default: '' },
        flightNumber: { type: String, default: '' },
        pnrCode: { type: String, default: '' },
        bookingRef: { type: String, default: '' },
        fromCity: { type: String, default: '' },
        toCity: { type: String, default: '' },
        departureDate: { type: String, default: '' },
        departureTime: { type: String, default: '' },
        arrivalDate: { type: String, default: '' },
        arrivalTime: { type: String, default: '' },
        seatClass: { type: String, default: '' },
        baggageAllowance: { type: String, default: '' },
        transitInfo: { type: String, default: '' },
        hotelName: { type: String, default: '' },
        checkInDate: { type: String, default: '' },
        checkOutDate: { type: String, default: '' },
        roomType: { type: String, default: '' },
        hotelAddress: { type: String, default: '' },
        phone: { type: String, default: '' },
        email: { type: String, default: '' },
        address: { type: String, default: '' },
        ticketPrice: { type: String, default: '' },
        currency: { type: String, default: 'BDT' },
        visaFee: { type: String, default: '' },
        remarks: { type: String, default: '' },
        agencyName: { type: String, default: 'VisaPro Consultancy & Migration' },
        agencyPhone: { type: String, default: '+880 1712-114770' },
        agencyEmail: { type: String, default: 'info@visaprocm.com' },
        agencyWebsite: { type: String, default: 'www.visaprocm.com' },
        agencyOffice: { type: String, default: 'Dhaka, Bangladesh' },
    },
    { timestamps: true, versionKey: false }
);

docEntrySchema.index({ createdAt: -1 });
docEntrySchema.index({ fullNameEn: 'text', documentNumber: 'text' });

export const DocEntry = model('DocEntry', docEntrySchema);
